/**
 * Auto-generated by scripts/generate-sitemaps.mjs — do not edit.
 */
export async function onRequest(context) {
  const url = new URL(context.request.url)
  url.pathname = '/sitemap.xml'
  url.search = ''
  const asset = await context.env.ASSETS.fetch(new Request(url, context.request))
  if (!asset.ok) {
    return new Response('Sitemap unavailable', { status: 503 })
  }
  const body = await asset.text()
  if (!body.trimStart().startsWith('<?xml')) {
    return new Response('Invalid sitemap asset', { status: 500 })
  }
  return new Response(body, {
    status: 200,
    headers: {
      'Content-Type': 'application/xml; charset=utf-8',
      'Cache-Control': 'public, max-age=3600',
    },
  })
}
