/**
 * Auto-generated by scripts/generate-sitemaps.mjs — do not edit.
 */
export async function onRequest(context) {
  const target = new URL('/sitemap', context.request.url)
  return Response.redirect(target.toString(), 301)
}
