/** Auto-generated by scripts/generate-isle-forums.mjs — edit the script and re-run. */
export type BlogSection = {
  heading: string
  body: string[]
}

export type BlogPost = {
  slug: string
  title: string
  excerpt: string
  metaTitle: string
  metaDescription: string
  searchTerms: string
  date: string
  readMinutes: number
  tag: string
  sections: BlogSection[]
  howTo?: boolean
}

export const BLOGS: BlogPost[] = [
  {
    "slug": "features-list",
    "title": "The Isle Cheats Features",
    "excerpt": "Full visual and misc module checklist for the isle cheats on PC — player ESP, NPC and animal overlays, snaplines, growth readouts, and misc utilities before checkout.",
    "metaTitle": "The Isle Cheats Features | Full Feature Overview",
    "metaDescription": "Full visual and misc module checklist for the isle cheats on PC — player ESP, NPC and animal overlays, snaplines, growth readouts, and misc utilities befor.",
    "searchTerms": "the isle cheats, the isle game cheat, the isle evrima cheats, the isle esp",
    "date": "2026-09-12",
    "readMinutes": 6,
    "tag": "Features",
    "sections": [
      {
        "heading": "What the menu includes",
        "body": [
          "This thread mirrors the live module list on buyislecheats.com. Compare player ESP, corpse and water markers, misc crosshair and fullbright toggles against how you survive in Evrima.",
          "The Isle is a dinosaur survival sim — awareness overlays matter more than arcade aim helpers. Start ESP-first, then tune misc keys."
        ]
      },
      {
        "heading": "Visual and misc stacks",
        "body": [
          "Visual options cover player, NPC, and animal ESP with box, snapline, name, distance, corpse, health, stamina, growth, species, direction, head dot, visible check, gore, fruit, water, and max distance.",
          "Misc options include crosshair, suicide, fullbright, FPS/resolution/time readouts, custom menu and panic keys, and custom ESP colors."
        ]
      }
    ]
  },
  {
    "slug": "complete-setup",
    "title": "Instructions to Use the Cheats",
    "excerpt": "Step-by-step the isle cheats setup on Windows: confirm Active status, exclusions, load order, first ESP profile, save config, and Evrima branch notes.",
    "metaTitle": "Instructions to Use the Cheats | The Isle Cheats Forum",
    "metaDescription": "Step-by-step the isle cheats setup on Windows: confirm Active status, exclusions, load order, first ESP profile, save config, and Evrima branch notes.",
    "searchTerms": "the isle cheats, the isle evrima cheats",
    "date": "2026-09-13",
    "readMinutes": 7,
    "tag": "Setup",
    "sections": [
      {
        "heading": "1) Confirm status and checkout",
        "body": [
          "Open buyislecheats.com and check Active on the product card. When Updating after an Evrima patch, wait — loading early wastes a growth session.",
          "Plans start from $35 monthly with lifetime options; use only the delivery link from your order email."
        ]
      },
      {
        "heading": "2) Windows prep",
        "body": [
          "Close Discord overlay, GeForce overlay, and RGB hooks. Add the delivery folder to Defender exclusions before first inject."
        ]
      },
      {
        "heading": "3) Load order",
        "body": [
          "Launch The Isle Evrima, reach the menu, run the loader, open the overlay menu, enable player ESP with distance caps, then add misc toggles only if you need them."
        ]
      }
    ],
    "howTo": true
  },
  {
    "slug": "the-isle-cheats-guide",
    "title": "The Isle Cheats Guide: Safety, Features, and Survival Tips",
    "excerpt": "Core the isle cheats guide — safe setup habits, ESP-first survival, growth pacing, and when to pause after Evrima updates.",
    "metaTitle": "The Isle Cheats Guide: Safety, Features, and Survival Tips | The Isle Cheats Forum",
    "metaDescription": "Core the isle cheats guide — safe setup habits, ESP-first survival, growth pacing, and when to pause after Evrima updates.",
    "searchTerms": "the isle cheats, the isle game cheat",
    "date": "2026-09-14",
    "readMinutes": 8,
    "tag": "Guide",
    "sections": [
      {
        "heading": "Safety and habits",
        "body": [
          "Read loader status before every session. Conservative ESP distance and visible check reduce noisy reports in crowded herbivore beaches.",
          "This site covers The Isle only — no multi-game catalog."
        ]
      }
    ]
  },
  {
    "slug": "the-isle-evrima-cheats-recode",
    "title": "The Isle Evrima Cheats: What You Need to Know for the Recode",
    "excerpt": "the isle cheats evrima and the isle evrima cheats explained — branch differences, overlay compatibility, and patch-day checklists for the recode client.",
    "metaTitle": "The Isle Evrima Cheats: What You Need to Know for the Recode | The Isle Cheats Forum",
    "metaDescription": "the isle cheats evrima and the isle evrima cheats explained — branch differences, overlay compatibility, and patch-day checklists for the recode client.",
    "searchTerms": "the isle cheats evrima, the isle evrima cheats, the isle evrima cheat",
    "date": "2026-09-15",
    "readMinutes": 9,
    "tag": "Evrima",
    "sections": [
      {
        "heading": "Evrima-only focus",
        "body": [
          "Modules target the Evrima branch on Windows PC. Legacy legacy branch players should verify server rules before loading any overlay.",
          "Status labels on buyislecheats.com track Evrima builds — do not inject while Updating."
        ]
      }
    ]
  },
  {
    "slug": "advanced-esp-tactics",
    "title": "Advanced ESP Tactics: Using The Isle ESP to Survive",
    "excerpt": "Advanced the isle esp tactics — layering player, NPC, and animal ESP with snaplines, species tags, and max distance for Evrima hunts.",
    "metaTitle": "Advanced ESP Tactics: Using The Isle ESP to Survive | The Isle Cheats Forum",
    "metaDescription": "Advanced the isle esp tactics — layering player, NPC, and animal ESP with snaplines, species tags, and max distance for Evrima hunts.",
    "searchTerms": "the isle esp, esp the isle, the isle esp cheat, the isle evrima esp",
    "date": "2026-09-16",
    "readMinutes": 10,
    "tag": "ESP",
    "sections": [
      {
        "heading": "ESP layering",
        "body": [
          "Enable player ESP with distance and species first. Add corpse and water markers when you play herbivore growth paths.",
          "the isle esp cheat searches often mean wallhack-style awareness — keep visible check on when peeking through dense foliage."
        ]
      }
    ],
    "howTo": true
  },
  {
    "slug": "best-the-isle-cheats-review-2026",
    "title": "Best The Isle Cheats Review & Comparison 2026: Features, Safety & Value",
    "excerpt": "2026 the isle cheats comparison — ESP clarity, Evrima maintenance, pricing from $35, config save habits, and loader transparency.",
    "metaTitle": "Best The Isle Cheats Review & Comparison 2026: Features, Safety & Value | The Isle Cheats Forum",
    "metaDescription": "2026 the isle cheats comparison — ESP clarity, Evrima maintenance, pricing from $35, config save habits, and loader transparency.",
    "searchTerms": "the isle cheats, the isle game cheat, the isle cheats evrima",
    "date": "2026-09-17",
    "readMinutes": 6,
    "tag": "Review",
    "sections": [
      {
        "heading": "What we compared",
        "body": [
          "Module depth for dinosaur ESP, misc utility keys, status pages, and how fast overlays recovered after Evrima patches — not hype claims."
        ]
      }
    ]
  },
  {
    "slug": "hwid-spoofer-safety",
    "title": "Discover What an HWID Spoofer Does for Safety",
    "excerpt": "HWID spoofer basics for PC gamers — hardware IDs, why some players research them, and realistic limits alongside loader discipline.",
    "metaTitle": "Discover What an HWID Spoofer Does for Safety | The Isle Cheats Forum",
    "metaDescription": "HWID spoofer basics for PC gamers — hardware IDs, why some players research them, and realistic limits alongside loader discipline.",
    "searchTerms": "The Isle Safety, hwid spoofer safety, The Isle cheats",
    "date": "2026-09-18",
    "readMinutes": 7,
    "tag": "Safety",
    "sections": [
      {
        "heading": "Plain-language overview",
        "body": [
          "A spoofer changes how your PC fingerprint appears to some anti-cheat stacks. It is not a substitute for reading loader status or playing conservatively."
        ]
      }
    ]
  },
  {
    "slug": "buy-the-isle-cheats-safely",
    "title": "Where to Buy The Isle Cheats Safely: Plans and Delivery",
    "excerpt": "How to buy the isle cheats with clear pricing, digital delivery, and Active status labels before you load into Evrima.",
    "metaTitle": "Where to Buy The Isle Cheats Safely: Plans and Delivery | The Isle Cheats Forum",
    "metaDescription": "How to buy the isle cheats with clear pricing, digital delivery, and Active status labels before you load into Evrima.",
    "searchTerms": "the isle cheats, the isle evrima cheat",
    "date": "2026-09-19",
    "readMinutes": 8,
    "tag": "Buying",
    "sections": [
      {
        "heading": "Before checkout",
        "body": [
          "Use buyislecheats.com for live Active/Updating status. Monthly and lifetime licenses include loader updates when status allows."
        ]
      }
    ]
  },
  {
    "slug": "the-isle-cheats-lifetime",
    "title": "The Isle Cheats Lifetime License: Is Permanent Access Worth It?",
    "excerpt": "Lifetime vs monthly the isle cheats access — when permanent makes sense for regular Evrima survival players.",
    "metaTitle": "The Isle Cheats Lifetime License: Is Permanent Access Worth It? | The Isle Cheats Forum",
    "metaDescription": "Lifetime vs monthly the isle cheats access — when permanent makes sense for regular Evrima survival players.",
    "searchTerms": "the isle cheats, the isle evrima cheats",
    "date": "2026-09-20",
    "readMinutes": 9,
    "tag": "Pricing",
    "sections": [
      {
        "heading": "Who lifetime fits",
        "body": [
          "If you grow dinosaurs multiple nights per week through seasons, lifetime offsets monthly renewals. Casual players often start monthly first."
        ]
      }
    ]
  },
  {
    "slug": "player-esp-first",
    "title": "Player ESP Settings: What to Enable First",
    "excerpt": "Configure the isle esp player overlays — box, snapline, distance, species, and growth tags without cluttering jungle fights.",
    "metaTitle": "Player ESP Settings: What to Enable First | The Isle Cheats Forum",
    "metaDescription": "Configure the isle esp player overlays — box, snapline, distance, species, and growth tags without cluttering jungle fights.",
    "searchTerms": "the isle esp, the isle esp cheat",
    "date": "2026-09-21",
    "readMinutes": 10,
    "tag": "ESP",
    "sections": [
      {
        "heading": "Recommended first toggles",
        "body": [
          "Enable box, distance, and species. Add stamina readouts when you hunt apex predators — tire them before you commit.",
          "Cap max distance around 200–300m so tags stay readable during beach spawns."
        ]
      }
    ],
    "howTo": true
  },
  {
    "slug": "silent-aim-overview",
    "title": "Silent Aim and Combat Assist for The Isle",
    "excerpt": "Overview of silent aim style assist on The Isle — when to keep combat modules off and rely on ESP awareness instead.",
    "metaTitle": "Silent Aim and Combat Assist for The Isle | The Isle Cheats Forum",
    "metaDescription": "Overview of silent aim style assist on The Isle — when to keep combat modules off and rely on ESP awareness instead.",
    "searchTerms": "The Isle Combat, silent aim overview, The Isle cheats",
    "date": "2026-09-12",
    "readMinutes": 6,
    "tag": "Combat",
    "sections": [
      {
        "heading": "Combat assist reality",
        "body": [
          "Many players run ESP-only for growth. If you enable assist, keep settings conservative — dinosaur fights are slow and highly visible."
        ]
      }
    ]
  },
  {
    "slug": "game-patch-status",
    "title": "The Isle Cheats After a Game Patch — What to Do",
    "excerpt": "What Active vs Updating means after Evrima patches — and why loading early wastes your dinosaur growth session.",
    "metaTitle": "The Isle Cheats After a Game Patch — What to Do | The Isle Cheats Forum",
    "metaDescription": "What Active vs Updating means after Evrima patches — and why loading early wastes your dinosaur growth session.",
    "searchTerms": "the isle evrima cheats, the isle cheats evrima",
    "date": "2026-09-13",
    "readMinutes": 7,
    "tag": "Status",
    "sections": [
      {
        "heading": "Status labels",
        "body": [
          "Active means the loader matches the live client. Updating means wait — check buyislecheats.com before every session."
        ]
      }
    ]
  },
  {
    "slug": "windows-setup",
    "title": "The Isle Cheats on Windows 10 and 11",
    "excerpt": "Windows prep for the isle cheats — overlays, Defender, and Evrima Steam launch order.",
    "metaTitle": "The Isle Cheats on Windows 10 and 11 | The Isle Cheats Forum",
    "metaDescription": "Windows prep for the isle cheats — overlays, Defender, and Evrima Steam launch order.",
    "searchTerms": "The Isle Windows, windows setup, The Isle cheats",
    "date": "2026-09-14",
    "readMinutes": 8,
    "tag": "Windows",
    "sections": [
      {
        "heading": "Supported systems",
        "body": [
          "Windows 10/11 with The Isle Evrima on Steam — close overlays before inject."
        ]
      }
    ],
    "howTo": true
  },
  {
    "slug": "disable-antivirus",
    "title": "Antivirus Exclusions for The Isle Cheats",
    "excerpt": "Allowlist loaders in Defender so files are not quarantined mid-setup.",
    "metaTitle": "Antivirus Exclusions for The Isle Cheats | The Isle Cheats Forum",
    "metaDescription": "Allowlist loaders in Defender so files are not quarantined mid-setup.",
    "searchTerms": "The Isle Antivirus, disable antivirus, The Isle cheats",
    "date": "2026-09-15",
    "readMinutes": 9,
    "tag": "Antivirus",
    "sections": [
      {
        "heading": "Defender",
        "body": [
          "Folder exclusion before first run — restore quarantines if you retried blindly."
        ]
      }
    ],
    "howTo": true
  },
  {
    "slug": "hotkeys",
    "title": "The Isle Cheat Hotkeys After Load",
    "excerpt": "Menu, panic, and ESP master hotkeys — custom menu key and panic key configuration.",
    "metaTitle": "The Isle Cheat Hotkeys After Load | The Isle Cheats Forum",
    "metaDescription": "Menu, panic, and ESP master hotkeys — custom menu key and panic key configuration.",
    "searchTerms": "The Isle Hotkeys, hotkeys, The Isle cheats",
    "date": "2026-09-16",
    "readMinutes": 10,
    "tag": "Hotkeys",
    "sections": [
      {
        "heading": "Suggested binds",
        "body": [
          "Menu toggle, ESP master, panic hide — write them down once and mirror the misc options forum."
        ]
      }
    ],
    "howTo": true
  },
  {
    "slug": "loader-errors",
    "title": "Fix The Isle Cheat Loader Errors",
    "excerpt": "Menu not opening, instant close, antivirus quarantine, failed inject on Evrima.",
    "metaTitle": "Fix The Isle Cheat Loader Errors | The Isle Cheats Forum",
    "metaDescription": "Menu not opening, instant close, antivirus quarantine, failed inject on Evrima.",
    "searchTerms": "The Isle Support, loader errors, The Isle cheats",
    "date": "2026-09-17",
    "readMinutes": 6,
    "tag": "Support",
    "sections": [
      {
        "heading": "Check status first",
        "body": [
          "Updating builds fail for reasons settings cannot fix — confirm Active."
        ]
      }
    ],
    "howTo": true
  },
  {
    "slug": "load-status-checklist",
    "title": "Pre-Load Checklist Before You Buy or Queue",
    "excerpt": "Confirm Active status, game version, and config before long Evrima growth sessions.",
    "metaTitle": "Pre-Load Checklist Before You Buy or Queue | The Isle Cheats Forum",
    "metaDescription": "Confirm Active status, game version, and config before long Evrima growth sessions.",
    "searchTerms": "The Isle Status, load status checklist, The Isle cheats",
    "date": "2026-09-18",
    "readMinutes": 7,
    "tag": "Status",
    "sections": [
      {
        "heading": "Before checkout",
        "body": [
          "Confirm Active on buyislecheats.com. If Updating, wait or read refunds policy."
        ]
      }
    ]
  },
  {
    "slug": "complete-visual-options-breakdown",
    "title": "Complete Visual Options Breakdown for The Isle",
    "excerpt": "Complete Visual Options Breakdown for The Isle for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD. Thread 1.",
    "metaTitle": "Complete Visual Options Breakdown for The Isle | The Isle Cheats Forum",
    "metaDescription": "Complete Visual Options Breakdown for The Isle for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD. Thre.",
    "searchTerms": "The Isle Visuals, complete visual options breakdown, The Isle cheats",
    "date": "2026-09-19",
    "readMinutes": 8,
    "tag": "Visuals",
    "sections": [
      {
        "heading": "Thread overview",
        "body": [
          "This guide maps \"Complete Visual Options Breakdown for The Isle\" to the live visual and misc menu on buyislecheats.com.",
          "Test in safe zones first: Evrima forests hide ambushes, and max-distance filters keep night hunts readable."
        ]
      }
    ]
  },
  {
    "slug": "player-esp-tracking",
    "title": "Player ESP Tracking: Never Get Ambushed in The Isle",
    "excerpt": "Player ESP Tracking: Never Get Ambushed in The Isle for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD. Thread 2.",
    "metaTitle": "Player ESP Tracking: Never Get Ambushed in The Isle | The Isle Cheats Forum",
    "metaDescription": "Player ESP Tracking: Never Get Ambushed in The Isle for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD.",
    "searchTerms": "the isle esp, esp the isle",
    "date": "2026-09-20",
    "readMinutes": 9,
    "tag": "ESP",
    "sections": [
      {
        "heading": "Thread overview",
        "body": [
          "This guide maps \"Player ESP Tracking: Never Get Ambushed in The Isle\" to the live visual and misc menu on buyislecheats.com.",
          "Test in safe zones first: Evrima forests hide ambushes, and max-distance filters keep night hunts readable."
        ]
      }
    ]
  },
  {
    "slug": "npc-esp-guide",
    "title": "NPC ESP Guide: Locating AI Dinosaurs Quickly",
    "excerpt": "NPC ESP Guide: Locating AI Dinosaurs Quickly for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD. Thread 3.",
    "metaTitle": "NPC ESP Guide: Locating AI Dinosaurs Quickly | The Isle Cheats Forum",
    "metaDescription": "NPC ESP Guide: Locating AI Dinosaurs Quickly for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD. Thread.",
    "searchTerms": "The Isle ESP, npc esp guide, The Isle cheats",
    "date": "2026-09-21",
    "readMinutes": 10,
    "tag": "ESP",
    "sections": [
      {
        "heading": "Thread overview",
        "body": [
          "This guide maps \"NPC ESP Guide: Locating AI Dinosaurs Quickly\" to the live visual and misc menu on buyislecheats.com.",
          "Test in safe zones first: Evrima forests hide ambushes, and max-distance filters keep night hunts readable."
        ]
      }
    ]
  },
  {
    "slug": "animal-esp-features",
    "title": "Animal ESP Features: Finding Food and Prey Easily",
    "excerpt": "Animal ESP Features: Finding Food and Prey Easily for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD. Thread 4.",
    "metaTitle": "Animal ESP Features: Finding Food and Prey Easily | The Isle Cheats Forum",
    "metaDescription": "Animal ESP Features: Finding Food and Prey Easily for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD. T.",
    "searchTerms": "The Isle ESP, animal esp features, The Isle cheats",
    "date": "2026-09-12",
    "readMinutes": 6,
    "tag": "ESP",
    "sections": [
      {
        "heading": "Thread overview",
        "body": [
          "This guide maps \"Animal ESP Features: Finding Food and Prey Easily\" to the live visual and misc menu on buyislecheats.com.",
          "Test in safe zones first: Evrima forests hide ambushes, and max-distance filters keep night hunts readable."
        ]
      }
    ]
  },
  {
    "slug": "box-esp-overlays",
    "title": "Box ESP Overlays for Clear Target Distances",
    "excerpt": "Box ESP Overlays for Clear Target Distances for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD. Thread 5.",
    "metaTitle": "Box ESP Overlays for Clear Target Distances | The Isle Cheats Forum",
    "metaDescription": "Box ESP Overlays for Clear Target Distances for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD. Thread .",
    "searchTerms": "The Isle Visuals, box esp overlays, The Isle cheats",
    "date": "2026-09-13",
    "readMinutes": 7,
    "tag": "Visuals",
    "sections": [
      {
        "heading": "Thread overview",
        "body": [
          "This guide maps \"Box ESP Overlays for Clear Target Distances\" to the live visual and misc menu on buyislecheats.com.",
          "Test in safe zones first: Evrima forests hide ambushes, and max-distance filters keep night hunts readable."
        ]
      }
    ]
  },
  {
    "slug": "snapline-overlays",
    "title": "Snapline Overlays: Instantly Spot Player Directions",
    "excerpt": "Snapline Overlays: Instantly Spot Player Directions for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD. Thread 6.",
    "metaTitle": "Snapline Overlays: Instantly Spot Player Directions | The Isle Cheats Forum",
    "metaDescription": "Snapline Overlays: Instantly Spot Player Directions for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD.",
    "searchTerms": "The Isle Visuals, snapline overlays, The Isle cheats",
    "date": "2026-09-14",
    "readMinutes": 8,
    "tag": "Visuals",
    "sections": [
      {
        "heading": "Thread overview",
        "body": [
          "This guide maps \"Snapline Overlays: Instantly Spot Player Directions\" to the live visual and misc menu on buyislecheats.com.",
          "Test in safe zones first: Evrima forests hide ambushes, and max-distance filters keep night hunts readable."
        ]
      }
    ]
  },
  {
    "slug": "player-name-tags",
    "title": "Player Name Tags: Identifying Species and Players at Range",
    "excerpt": "Player Name Tags: Identifying Species and Players at Range for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD. Thread 7.",
    "metaTitle": "Player Name Tags: Identifying Species and Players at Range | The Isle Cheats Forum",
    "metaDescription": "Player Name Tags: Identifying Species and Players at Range for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming yo.",
    "searchTerms": "The Isle Visuals, player name tags, The Isle cheats",
    "date": "2026-09-15",
    "readMinutes": 9,
    "tag": "Visuals",
    "sections": [
      {
        "heading": "Thread overview",
        "body": [
          "This guide maps \"Player Name Tags: Identifying Species and Players at Range\" to the live visual and misc menu on buyislecheats.com.",
          "Test in safe zones first: Evrima forests hide ambushes, and max-distance filters keep night hunts readable."
        ]
      }
    ]
  },
  {
    "slug": "distance-indicators",
    "title": "Distance Indicators for Strategic Survival Positioning",
    "excerpt": "Distance Indicators for Strategic Survival Positioning for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD. Thread 8.",
    "metaTitle": "Distance Indicators for Strategic Survival Positioning | The Isle Cheats Forum",
    "metaDescription": "Distance Indicators for Strategic Survival Positioning for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your H.",
    "searchTerms": "The Isle Visuals, distance indicators, The Isle cheats",
    "date": "2026-09-16",
    "readMinutes": 10,
    "tag": "Visuals",
    "sections": [
      {
        "heading": "Thread overview",
        "body": [
          "This guide maps \"Distance Indicators for Strategic Survival Positioning\" to the live visual and misc menu on buyislecheats.com.",
          "Test in safe zones first: Evrima forests hide ambushes, and max-distance filters keep night hunts readable."
        ]
      }
    ]
  },
  {
    "slug": "corpse-esp",
    "title": "Corpse ESP: Locating Food Sources Across the Map",
    "excerpt": "Corpse ESP: Locating Food Sources Across the Map for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD. Thread 9.",
    "metaTitle": "Corpse ESP: Locating Food Sources Across the Map | The Isle Cheats Forum",
    "metaDescription": "Corpse ESP: Locating Food Sources Across the Map for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD. Th.",
    "searchTerms": "The Isle Visuals, corpse esp, The Isle cheats",
    "date": "2026-09-17",
    "readMinutes": 6,
    "tag": "Visuals",
    "sections": [
      {
        "heading": "Thread overview",
        "body": [
          "This guide maps \"Corpse ESP: Locating Food Sources Across the Map\" to the live visual and misc menu on buyislecheats.com.",
          "Test in safe zones first: Evrima forests hide ambushes, and max-distance filters keep night hunts readable."
        ]
      }
    ]
  },
  {
    "slug": "health-tracking-overlays",
    "title": "Health Tracking Overlays for Combat Advantage",
    "excerpt": "Health Tracking Overlays for Combat Advantage for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD. Thread 10.",
    "metaTitle": "Health Tracking Overlays for Combat Advantage | The Isle Cheats Forum",
    "metaDescription": "Health Tracking Overlays for Combat Advantage for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD. Threa.",
    "searchTerms": "The Isle Visuals, health tracking overlays, The Isle cheats",
    "date": "2026-09-18",
    "readMinutes": 7,
    "tag": "Visuals",
    "sections": [
      {
        "heading": "Thread overview",
        "body": [
          "This guide maps \"Health Tracking Overlays for Combat Advantage\" to the live visual and misc menu on buyislecheats.com.",
          "Test in safe zones first: Evrima forests hide ambushes, and max-distance filters keep night hunts readable."
        ]
      }
    ]
  },
  {
    "slug": "stamina-status-display",
    "title": "Stamina Status Display for Predator Pursuits",
    "excerpt": "Stamina Status Display for Predator Pursuits for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD. Thread 11.",
    "metaTitle": "Stamina Status Display for Predator Pursuits | The Isle Cheats Forum",
    "metaDescription": "Stamina Status Display for Predator Pursuits for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD. Thread.",
    "searchTerms": "The Isle Visuals, stamina status display, The Isle cheats",
    "date": "2026-09-19",
    "readMinutes": 8,
    "tag": "Visuals",
    "sections": [
      {
        "heading": "Thread overview",
        "body": [
          "This guide maps \"Stamina Status Display for Predator Pursuits\" to the live visual and misc menu on buyislecheats.com.",
          "Test in safe zones first: Evrima forests hide ambushes, and max-distance filters keep night hunts readable."
        ]
      }
    ]
  },
  {
    "slug": "growth-tracker",
    "title": "Growth Tracker: Monitoring Your Dinosaur Maturation Stage",
    "excerpt": "Growth Tracker: Monitoring Your Dinosaur Maturation Stage for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD. Thread 12.",
    "metaTitle": "Growth Tracker: Monitoring Your Dinosaur Maturation Stage | The Isle Cheats Forum",
    "metaDescription": "Growth Tracker: Monitoring Your Dinosaur Maturation Stage for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming you.",
    "searchTerms": "The Isle Visuals, growth tracker, The Isle cheats",
    "date": "2026-09-20",
    "readMinutes": 9,
    "tag": "Visuals",
    "sections": [
      {
        "heading": "Thread overview",
        "body": [
          "This guide maps \"Growth Tracker: Monitoring Your Dinosaur Maturation Stage\" to the live visual and misc menu on buyislecheats.com.",
          "Test in safe zones first: Evrima forests hide ambushes, and max-distance filters keep night hunts readable."
        ]
      }
    ]
  },
  {
    "slug": "species-identification-esp",
    "title": "Species Identification ESP: Know Your Threat Level",
    "excerpt": "Species Identification ESP: Know Your Threat Level for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD. Thread 13.",
    "metaTitle": "Species Identification ESP: Know Your Threat Level | The Isle Cheats Forum",
    "metaDescription": "Species Identification ESP: Know Your Threat Level for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD. .",
    "searchTerms": "The Isle Visuals, species identification esp, The Isle cheats",
    "date": "2026-09-21",
    "readMinutes": 10,
    "tag": "Visuals",
    "sections": [
      {
        "heading": "Thread overview",
        "body": [
          "This guide maps \"Species Identification ESP: Know Your Threat Level\" to the live visual and misc menu on buyislecheats.com.",
          "Test in safe zones first: Evrima forests hide ambushes, and max-distance filters keep night hunts readable."
        ]
      }
    ]
  },
  {
    "slug": "player-direction-indicators",
    "title": "Player Direction Indicators to Anticipate Flanks",
    "excerpt": "Player Direction Indicators to Anticipate Flanks for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD. Thread 14.",
    "metaTitle": "Player Direction Indicators to Anticipate Flanks | The Isle Cheats Forum",
    "metaDescription": "Player Direction Indicators to Anticipate Flanks for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD. Th.",
    "searchTerms": "The Isle Visuals, player direction indicators, The Isle cheats",
    "date": "2026-09-12",
    "readMinutes": 6,
    "tag": "Visuals",
    "sections": [
      {
        "heading": "Thread overview",
        "body": [
          "This guide maps \"Player Direction Indicators to Anticipate Flanks\" to the live visual and misc menu on buyislecheats.com.",
          "Test in safe zones first: Evrima forests hide ambushes, and max-distance filters keep night hunts readable."
        ]
      }
    ]
  },
  {
    "slug": "head-dot-precision",
    "title": "Head Dot Precision Overlay for Accurate Targeting",
    "excerpt": "Head Dot Precision Overlay for Accurate Targeting for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD. Thread 15.",
    "metaTitle": "Head Dot Precision Overlay for Accurate Targeting | The Isle Cheats Forum",
    "metaDescription": "Head Dot Precision Overlay for Accurate Targeting for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD. T.",
    "searchTerms": "The Isle Visuals, head dot precision, The Isle cheats",
    "date": "2026-09-13",
    "readMinutes": 7,
    "tag": "Visuals",
    "sections": [
      {
        "heading": "Thread overview",
        "body": [
          "This guide maps \"Head Dot Precision Overlay for Accurate Targeting\" to the live visual and misc menu on buyislecheats.com.",
          "Test in safe zones first: Evrima forests hide ambushes, and max-distance filters keep night hunts readable."
        ]
      }
    ]
  },
  {
    "slug": "visible-check-settings",
    "title": "Visible Check Settings to Avoid Wall Detection Issues",
    "excerpt": "Visible Check Settings to Avoid Wall Detection Issues for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD. Thread 16.",
    "metaTitle": "Visible Check Settings to Avoid Wall Detection Issues | The Isle Cheats Forum",
    "metaDescription": "Visible Check Settings to Avoid Wall Detection Issues for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HU.",
    "searchTerms": "The Isle Visuals, visible check settings, The Isle cheats",
    "date": "2026-09-14",
    "readMinutes": 8,
    "tag": "Visuals",
    "sections": [
      {
        "heading": "Thread overview",
        "body": [
          "This guide maps \"Visible Check Settings to Avoid Wall Detection Issues\" to the live visual and misc menu on buyislecheats.com.",
          "Test in safe zones first: Evrima forests hide ambushes, and max-distance filters keep night hunts readable."
        ]
      }
    ]
  },
  {
    "slug": "gore-visual-options",
    "title": "Gore Visual Options for Immersive Dinosaur Combat",
    "excerpt": "Gore Visual Options for Immersive Dinosaur Combat for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD. Thread 17.",
    "metaTitle": "Gore Visual Options for Immersive Dinosaur Combat | The Isle Cheats Forum",
    "metaDescription": "Gore Visual Options for Immersive Dinosaur Combat for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD. T.",
    "searchTerms": "The Isle Visuals, gore visual options, The Isle cheats",
    "date": "2026-09-15",
    "readMinutes": 9,
    "tag": "Visuals",
    "sections": [
      {
        "heading": "Thread overview",
        "body": [
          "This guide maps \"Gore Visual Options for Immersive Dinosaur Combat\" to the live visual and misc menu on buyislecheats.com.",
          "Test in safe zones first: Evrima forests hide ambushes, and max-distance filters keep night hunts readable."
        ]
      }
    ]
  },
  {
    "slug": "fruit-esp",
    "title": "Fruit ESP: Herbivore Food Hunting Made Simple",
    "excerpt": "Fruit ESP: Herbivore Food Hunting Made Simple for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD. Thread 18.",
    "metaTitle": "Fruit ESP: Herbivore Food Hunting Made Simple | The Isle Cheats Forum",
    "metaDescription": "Fruit ESP: Herbivore Food Hunting Made Simple for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD. Threa.",
    "searchTerms": "The Isle Visuals, fruit esp, The Isle cheats",
    "date": "2026-09-16",
    "readMinutes": 10,
    "tag": "Visuals",
    "sections": [
      {
        "heading": "Thread overview",
        "body": [
          "This guide maps \"Fruit ESP: Herbivore Food Hunting Made Simple\" to the live visual and misc menu on buyislecheats.com.",
          "Test in safe zones first: Evrima forests hide ambushes, and max-distance filters keep night hunts readable."
        ]
      }
    ]
  },
  {
    "slug": "water-source-esp",
    "title": "Water Source ESP: Never Die of Dehydration Again",
    "excerpt": "Water Source ESP: Never Die of Dehydration Again for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD. Thread 19.",
    "metaTitle": "Water Source ESP: Never Die of Dehydration Again | The Isle Cheats Forum",
    "metaDescription": "Water Source ESP: Never Die of Dehydration Again for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD. Th.",
    "searchTerms": "The Isle Visuals, water source esp, The Isle cheats",
    "date": "2026-09-17",
    "readMinutes": 6,
    "tag": "Visuals",
    "sections": [
      {
        "heading": "Thread overview",
        "body": [
          "This guide maps \"Water Source ESP: Never Die of Dehydration Again\" to the live visual and misc menu on buyislecheats.com.",
          "Test in safe zones first: Evrima forests hide ambushes, and max-distance filters keep night hunts readable."
        ]
      }
    ]
  },
  {
    "slug": "optimizing-max-distance-filters",
    "title": "Optimizing Max Distance Filters to Clear Your HUD",
    "excerpt": "Optimizing Max Distance Filters to Clear Your HUD for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD. Thread 20.",
    "metaTitle": "Optimizing Max Distance Filters to Clear Your HUD | The Isle Cheats Forum",
    "metaDescription": "Optimizing Max Distance Filters to Clear Your HUD for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD. T.",
    "searchTerms": "The Isle Visuals, optimizing max distance filters, The Isle cheats",
    "date": "2026-09-18",
    "readMinutes": 7,
    "tag": "Visuals",
    "sections": [
      {
        "heading": "Thread overview",
        "body": [
          "This guide maps \"Optimizing Max Distance Filters to Clear Your HUD\" to the live visual and misc menu on buyislecheats.com.",
          "Test in safe zones first: Evrima forests hide ambushes, and max-distance filters keep night hunts readable."
        ]
      }
    ]
  },
  {
    "slug": "miscellaneous-utility-settings",
    "title": "Miscellaneous Utility Settings for Optimized Gameplay",
    "excerpt": "Miscellaneous Utility Settings for Optimized Gameplay for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD. Thread 21.",
    "metaTitle": "Miscellaneous Utility Settings for Optimized Gameplay | The Isle Cheats Forum",
    "metaDescription": "Miscellaneous Utility Settings for Optimized Gameplay for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HU.",
    "searchTerms": "The Isle Misc, miscellaneous utility settings, The Isle cheats",
    "date": "2026-09-19",
    "readMinutes": 8,
    "tag": "Misc",
    "sections": [
      {
        "heading": "Thread overview",
        "body": [
          "This guide maps \"Miscellaneous Utility Settings for Optimized Gameplay\" to the live visual and misc menu on buyislecheats.com.",
          "Test in safe zones first: Evrima forests hide ambushes, and max-distance filters keep night hunts readable."
        ]
      }
    ]
  },
  {
    "slug": "custom-crosshair-overlays",
    "title": "Custom Crosshair Overlays for Aiming Assistance",
    "excerpt": "Custom Crosshair Overlays for Aiming Assistance for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD. Thread 22.",
    "metaTitle": "Custom Crosshair Overlays for Aiming Assistance | The Isle Cheats Forum",
    "metaDescription": "Custom Crosshair Overlays for Aiming Assistance for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD. Thr.",
    "searchTerms": "The Isle Misc, custom crosshair overlays, The Isle cheats",
    "date": "2026-09-20",
    "readMinutes": 9,
    "tag": "Misc",
    "sections": [
      {
        "heading": "Thread overview",
        "body": [
          "This guide maps \"Custom Crosshair Overlays for Aiming Assistance\" to the live visual and misc menu on buyislecheats.com.",
          "Test in safe zones first: Evrima forests hide ambushes, and max-distance filters keep night hunts readable."
        ]
      }
    ]
  },
  {
    "slug": "quick-suicide-command",
    "title": "Quick Suicide Command for Fast Respawns",
    "excerpt": "Quick Suicide Command for Fast Respawns for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD. Thread 23.",
    "metaTitle": "Quick Suicide Command for Fast Respawns | The Isle Cheats Forum",
    "metaDescription": "Quick Suicide Command for Fast Respawns for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD. Thread 23.",
    "searchTerms": "The Isle Misc, quick suicide command, The Isle cheats",
    "date": "2026-09-21",
    "readMinutes": 10,
    "tag": "Misc",
    "sections": [
      {
        "heading": "Thread overview",
        "body": [
          "This guide maps \"Quick Suicide Command for Fast Respawns\" to the live visual and misc menu on buyislecheats.com.",
          "Test in safe zones first: Evrima forests hide ambushes, and max-distance filters keep night hunts readable."
        ]
      }
    ]
  },
  {
    "slug": "fullbright-visuals",
    "title": "Fullbright Visuals: See Clearly in Dark Night Cycles",
    "excerpt": "Fullbright Visuals: See Clearly in Dark Night Cycles for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD. Thread 24.",
    "metaTitle": "Fullbright Visuals: See Clearly in Dark Night Cycles | The Isle Cheats Forum",
    "metaDescription": "Fullbright Visuals: See Clearly in Dark Night Cycles for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD.",
    "searchTerms": "The Isle Misc, fullbright visuals, The Isle cheats",
    "date": "2026-09-12",
    "readMinutes": 6,
    "tag": "Misc",
    "sections": [
      {
        "heading": "Thread overview",
        "body": [
          "This guide maps \"Fullbright Visuals: See Clearly in Dark Night Cycles\" to the live visual and misc menu on buyislecheats.com.",
          "Test in safe zones first: Evrima forests hide ambushes, and max-distance filters keep night hunts readable."
        ]
      }
    ]
  },
  {
    "slug": "performance-monitoring-fps",
    "title": "Performance Monitoring: Displaying FPS In-Game",
    "excerpt": "Performance Monitoring: Displaying FPS In-Game for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD. Thread 25.",
    "metaTitle": "Performance Monitoring: Displaying FPS In-Game | The Isle Cheats Forum",
    "metaDescription": "Performance Monitoring: Displaying FPS In-Game for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD. Thre.",
    "searchTerms": "The Isle Misc, performance monitoring fps, The Isle cheats",
    "date": "2026-09-13",
    "readMinutes": 7,
    "tag": "Misc",
    "sections": [
      {
        "heading": "Thread overview",
        "body": [
          "This guide maps \"Performance Monitoring: Displaying FPS In-Game\" to the live visual and misc menu on buyislecheats.com.",
          "Test in safe zones first: Evrima forests hide ambushes, and max-distance filters keep night hunts readable."
        ]
      }
    ]
  },
  {
    "slug": "resolution-display-tool",
    "title": "Resolution Display Tool for Custom Overlays",
    "excerpt": "Resolution Display Tool for Custom Overlays for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD. Thread 26.",
    "metaTitle": "Resolution Display Tool for Custom Overlays | The Isle Cheats Forum",
    "metaDescription": "Resolution Display Tool for Custom Overlays for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD. Thread .",
    "searchTerms": "The Isle Misc, resolution display tool, The Isle cheats",
    "date": "2026-09-14",
    "readMinutes": 8,
    "tag": "Misc",
    "sections": [
      {
        "heading": "Thread overview",
        "body": [
          "This guide maps \"Resolution Display Tool for Custom Overlays\" to the live visual and misc menu on buyislecheats.com.",
          "Test in safe zones first: Evrima forests hide ambushes, and max-distance filters keep night hunts readable."
        ]
      }
    ]
  },
  {
    "slug": "in-game-time-display",
    "title": "In-Game Time Display for Environmental Tracking",
    "excerpt": "In-Game Time Display for Environmental Tracking for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD. Thread 27.",
    "metaTitle": "In-Game Time Display for Environmental Tracking | The Isle Cheats Forum",
    "metaDescription": "In-Game Time Display for Environmental Tracking for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD. Thr.",
    "searchTerms": "The Isle Misc, in game time display, The Isle cheats",
    "date": "2026-09-15",
    "readMinutes": 9,
    "tag": "Misc",
    "sections": [
      {
        "heading": "Thread overview",
        "body": [
          "This guide maps \"In-Game Time Display for Environmental Tracking\" to the live visual and misc menu on buyislecheats.com.",
          "Test in safe zones first: Evrima forests hide ambushes, and max-distance filters keep night hunts readable."
        ]
      }
    ]
  },
  {
    "slug": "custom-menu-hotkey",
    "title": "Setting Up Your Custom Menu Hotkey for Quick Toggles",
    "excerpt": "Setting Up Your Custom Menu Hotkey for Quick Toggles for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD. Thread 28.",
    "metaTitle": "Setting Up Your Custom Menu Hotkey for Quick Toggles | The Isle Cheats Forum",
    "metaDescription": "Setting Up Your Custom Menu Hotkey for Quick Toggles for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD.",
    "searchTerms": "The Isle Misc, custom menu hotkey, The Isle cheats",
    "date": "2026-09-16",
    "readMinutes": 10,
    "tag": "Misc",
    "sections": [
      {
        "heading": "Thread overview",
        "body": [
          "This guide maps \"Setting Up Your Custom Menu Hotkey for Quick Toggles\" to the live visual and misc menu on buyislecheats.com.",
          "Test in safe zones first: Evrima forests hide ambushes, and max-distance filters keep night hunts readable."
        ]
      }
    ]
  },
  {
    "slug": "panic-key-configuration",
    "title": "Panic Key Configuration for Instant Overlay Hiding",
    "excerpt": "Panic Key Configuration for Instant Overlay Hiding for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD. Thread 29.",
    "metaTitle": "Panic Key Configuration for Instant Overlay Hiding | The Isle Cheats Forum",
    "metaDescription": "Panic Key Configuration for Instant Overlay Hiding for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD. .",
    "searchTerms": "The Isle Misc, panic key configuration, The Isle cheats",
    "date": "2026-09-17",
    "readMinutes": 6,
    "tag": "Misc",
    "sections": [
      {
        "heading": "Thread overview",
        "body": [
          "This guide maps \"Panic Key Configuration for Instant Overlay Hiding\" to the live visual and misc menu on buyislecheats.com.",
          "Test in safe zones first: Evrima forests hide ambushes, and max-distance filters keep night hunts readable."
        ]
      }
    ]
  },
  {
    "slug": "customizing-esp-colors",
    "title": "Customizing ESP Colors for Personal Visual Preference",
    "excerpt": "Customizing ESP Colors for Personal Visual Preference for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HUD. Thread 30.",
    "metaTitle": "Customizing ESP Colors for Personal Visual Preference | The Isle Cheats Forum",
    "metaDescription": "Customizing ESP Colors for Personal Visual Preference for The Isle Evrima — overlay toggles, distance filters, and survival habits without spamming your HU.",
    "searchTerms": "The Isle Misc, customizing esp colors, The Isle cheats",
    "date": "2026-09-18",
    "readMinutes": 7,
    "tag": "Misc",
    "sections": [
      {
        "heading": "Thread overview",
        "body": [
          "This guide maps \"Customizing ESP Colors for Personal Visual Preference\" to the live visual and misc menu on buyislecheats.com.",
          "Test in safe zones first: Evrima forests hide ambushes, and max-distance filters keep night hunts readable."
        ]
      }
    ]
  }
]

export function getBlog(slug: string) {
  return BLOGS.find((b) => b.slug === slug)
}

/** Related threads for forum footers — never includes the current slug. */
export function getRelatedForumThreads(slug: string, limit = 6): BlogPost[] {
  const current = getBlog(slug)
  if (!current) return []
  return BLOGS.filter((b) => b.slug !== slug)
    .sort((a, b) => {
      const tagRank = (p: BlogPost) => (p.tag === current.tag ? 0 : 1)
      const byTag = tagRank(a) - tagRank(b)
      if (byTag !== 0) return byTag
      return a.title.localeCompare(b.title)
    })
    .slice(0, limit)
}

export { blogPath } from './blog-paths'
