/** Auto-generated by scripts/generate-dota2-content.mjs */
export type ForumReplyRole = 'editor' | 'moderator' | 'member'

export type ForumReply = {
  author: string
  date: string
  body: string
  role?: ForumReplyRole
  replyToAuthor?: string
}

export const FORUM_REPLIES: Record<string, ForumReply[]> = {
  "dota-2-cheats-discussion": [
    {
      "author": "Dota2Cheats Editor",
      "role": "editor",
      "date": "2026-03-11",
      "body": "Editor: pinned General reference for r/dota2cheats. Matches buydota2cheats.com menu — confirm Active before ranked."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-17",
      "body": "Moderator: no key selling or Discord scams in replies. Official checkout only via buydota2cheats.com."
    },
    {
      "author": "AncientApparition",
      "role": "member",
      "date": "2026-03-13",
      "body": "Wide map vision on stream looks obvious. Dialed opacity down per ESP thread."
    },
    {
      "author": "offlane_tank",
      "role": "member",
      "date": "2026-03-14",
      "body": "Creep timer + last hit helper bumped my GPM in unranked testing — not magic but consistent."
    },
    {
      "author": "rune_greedy",
      "role": "member",
      "date": "2026-03-15",
      "body": "Followed the setup thread — hero ESP and ward timers came up first try after Defender exclusion."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-18",
      "body": "@AncientApparition — walk the General checklist in the OP, confirm Active on buydota2cheats.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "AncientApparition"
    },
    {
      "author": "Dota 2 Cheats Support",
      "role": "moderator",
      "date": "2026-03-19",
      "body": "@rune_greedy — walk the General checklist in the OP, confirm Active on buydota2cheats.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "rune_greedy"
    }
  ],
  "vac-anticheat-safety": [
    {
      "author": "Dota2Cheats Editor",
      "role": "editor",
      "date": "2026-03-09",
      "body": "Editor: pinned VAC reference for r/VACSafety. Matches buydota2cheats.com menu — confirm Active before ranked."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-15",
      "body": "Moderator: no key selling or Discord scams in replies. Official checkout only via buydota2cheats.com."
    },
    {
      "author": "rune_greedy",
      "role": "member",
      "date": "2026-03-23",
      "body": "VAC thread scared me straight — staying on smurf for overlay testing only."
    },
    {
      "author": "Dota2CheatsMod",
      "role": "member",
      "date": "2026-03-24",
      "body": "Map hack on low opacity plus ward ESP feels readable. Nobody flamed in all-chat yet."
    },
    {
      "author": "LoaderGhost",
      "role": "member",
      "date": "2026-03-25",
      "body": "Thought HWID spoofer replaces a ban — it does not. Read the safety blog."
    },
    {
      "author": "IT_guy_gaming",
      "role": "member",
      "date": "2026-03-26",
      "body": "Followed the setup thread — hero ESP and ward timers came up first try after Defender exclusion."
    },
    {
      "author": "irritated_panda",
      "role": "member",
      "date": "2026-03-27",
      "body": "Moderator @reply fixed my Updating loader mistake. Waited for Active like they said."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-18",
      "body": "@rune_greedy — walk the VAC checklist in the OP, confirm Active on buydota2cheats.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "rune_greedy"
    },
    {
      "author": "Dota 2 Cheats Support",
      "role": "moderator",
      "date": "2026-03-19",
      "body": "@IT_guy_gaming — walk the VAC checklist in the OP, confirm Active on buydota2cheats.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "IT_guy_gaming"
    }
  ],
  "complete-setup": [
    {
      "author": "Dota2Cheats Editor",
      "role": "editor",
      "date": "2026-03-11",
      "body": "Editor: pinned Setup reference for r/Dota2Setup. Matches buydota2cheats.com menu — confirm Active before ranked."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-13",
      "body": "Moderator: no key selling or Discord scams in replies. Official checkout only via buydota2cheats.com."
    },
    {
      "author": "LoaderGhost",
      "role": "member",
      "date": "2026-03-13",
      "body": "Thought HWID spoofer replaces a ban — it does not. Read the safety blog."
    },
    {
      "author": "IT_guy_gaming",
      "role": "member",
      "date": "2026-03-14",
      "body": "Followed the setup thread — hero ESP and ward timers came up first try after Defender exclusion."
    },
    {
      "author": "irritated_panda",
      "role": "member",
      "date": "2026-03-15",
      "body": "Moderator @reply fixed my Updating loader mistake. Waited for Active like they said."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-18",
      "body": "@LoaderGhost — walk the Setup checklist in the OP, confirm Active on buydota2cheats.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "LoaderGhost"
    },
    {
      "author": "Dota 2 Cheats Support",
      "role": "moderator",
      "date": "2026-03-19",
      "body": "@irritated_panda — walk the Setup checklist in the OP, confirm Active on buydota2cheats.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "irritated_panda"
    }
  ],
  "hero-esp-config": [
    {
      "author": "Dota2Cheats Editor",
      "role": "editor",
      "date": "2026-03-08",
      "body": "Editor: pinned ESP reference for r/HeroESP. Matches buydota2cheats.com menu — confirm Active before ranked."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-12",
      "body": "Moderator: no key selling or Discord scams in replies. Official checkout only via buydota2cheats.com."
    },
    {
      "author": "support_fan",
      "role": "member",
      "date": "2026-03-22",
      "body": "Monthly vs lifetime pricing confused me until Support replied same day."
    },
    {
      "author": "MoneyKing",
      "role": "member",
      "date": "2026-03-23",
      "body": "Lifetime plan paid off after the third month — still on Active after last Dota patch."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-18",
      "body": "@support_fan — walk the ESP checklist in the OP, confirm Active on buydota2cheats.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "support_fan"
    }
  ],
  "map-hack-fog-config": [
    {
      "author": "Dota2Cheats Editor",
      "role": "editor",
      "date": "2026-03-12",
      "body": "Editor: pinned Map reference for r/MapVision. Matches buydota2cheats.com menu — confirm Active before ranked."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-16",
      "body": "Moderator: no key selling or Discord scams in replies. Official checkout only via buydota2cheats.com."
    },
    {
      "author": "longterm_core",
      "role": "member",
      "date": "2026-03-14",
      "body": "Lifetime plan paid off after the third month — still on Active after last Dota patch."
    },
    {
      "author": "sandbox_only",
      "role": "member",
      "date": "2026-03-15",
      "body": "VAC thread scared me straight — staying on smurf for overlay testing only."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-18",
      "body": "@longterm_core — walk the Map checklist in the OP, confirm Active on buydota2cheats.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "longterm_core"
    },
    {
      "author": "Dota 2 Cheats Support",
      "role": "moderator",
      "date": "2026-03-19",
      "body": "@sandbox_only — walk the Map checklist in the OP, confirm Active on buydota2cheats.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "sandbox_only"
    }
  ],
  "buy-dota-2-cheats-safely": [
    {
      "author": "Dota2Cheats Editor",
      "role": "editor",
      "date": "2026-03-10",
      "body": "Editor: pinned Buying reference for r/Dota2Deals. Matches buydota2cheats.com menu — confirm Active before ranked."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-18",
      "body": "Moderator: no key selling or Discord scams in replies. Official checkout only via buydota2cheats.com."
    },
    {
      "author": "patch_day_survivor",
      "role": "member",
      "date": "2026-03-24",
      "body": "Followed the setup thread — hero ESP and ward timers came up first try after Defender exclusion."
    },
    {
      "author": "defender_hater",
      "role": "member",
      "date": "2026-03-25",
      "body": "Ranked thread is depressing but accurate. Reports stack if you play blatant."
    },
    {
      "author": "longterm_core",
      "role": "member",
      "date": "2026-03-26",
      "body": "Rosh timer callouts synced with our discord; fewer throw fights at 25 min."
    },
    {
      "author": "sandbox_only",
      "role": "member",
      "date": "2026-03-27",
      "body": "Lifetime plan paid off after the third month — still on Active after last Dota patch."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-18",
      "body": "@patch_day_survivor — walk the Buying checklist in the OP, confirm Active on buydota2cheats.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "patch_day_survivor"
    },
    {
      "author": "Dota 2 Cheats Support",
      "role": "moderator",
      "date": "2026-03-19",
      "body": "@sandbox_only — walk the Buying checklist in the OP, confirm Active on buydota2cheats.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "sandbox_only"
    }
  ],
  "game-patch-status": [
    {
      "author": "Dota2Cheats Editor",
      "role": "editor",
      "date": "2026-03-08",
      "body": "Editor: pinned Patches reference for r/PatchWatch. Matches buydota2cheats.com menu — confirm Active before ranked."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-14",
      "body": "Moderator: no key selling or Discord scams in replies. Official checkout only via buydota2cheats.com."
    },
    {
      "author": "memory_curious",
      "role": "member",
      "date": "2026-03-10",
      "body": "Loaded during Updating after a patch — instant close. Status page was right."
    },
    {
      "author": "mid_gpm",
      "role": "member",
      "date": "2026-03-11",
      "body": "Moderator @reply fixed my Updating loader mistake. Waited for Active like they said."
    },
    {
      "author": "behavior_score_1",
      "role": "member",
      "date": "2026-03-12",
      "body": "Rosh timer callouts synced with our discord; fewer throw fights at 25 min."
    },
    {
      "author": "AncientApparition",
      "role": "member",
      "date": "2026-03-13",
      "body": "Expected cheat engine tips here — mod locked it and pointed to VAC FAQ. Fair."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-18",
      "body": "@memory_curious — walk the Patches checklist in the OP, confirm Active on buydota2cheats.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "memory_curious"
    }
  ],
  "loader-errors": [
    {
      "author": "Dota2Cheats Editor",
      "role": "editor",
      "date": "2026-03-11",
      "body": "Editor: pinned Support reference for r/LoaderHelp. Matches buydota2cheats.com menu — confirm Active before ranked."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-17",
      "body": "Moderator: no key selling or Discord scams in replies. Official checkout only via buydota2cheats.com."
    },
    {
      "author": "LoaderGhost",
      "role": "member",
      "date": "2026-03-13",
      "body": "Menu never opened until I restored Defender quarantine. Skipped that step first time."
    },
    {
      "author": "IT_guy_gaming",
      "role": "member",
      "date": "2026-03-14",
      "body": "Map hack on low opacity plus ward ESP feels readable. Nobody flamed in all-chat yet."
    },
    {
      "author": "irritated_panda",
      "role": "member",
      "date": "2026-03-15",
      "body": "Creep timer + last hit helper bumped my GPM in unranked testing — not magic but consistent."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-18",
      "body": "@LoaderGhost — walk the Support checklist in the OP, confirm Active on buydota2cheats.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "LoaderGhost"
    },
    {
      "author": "Dota 2 Cheats Support",
      "role": "moderator",
      "date": "2026-03-19",
      "body": "@irritated_panda — walk the Support checklist in the OP, confirm Active on buydota2cheats.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "irritated_panda"
    }
  ],
  "dota-2-cheats-lifetime": [
    {
      "author": "Dota2Cheats Editor",
      "role": "editor",
      "date": "2026-03-10",
      "body": "Editor: pinned Plans reference for r/Dota2Deals. Matches buydota2cheats.com menu — confirm Active before ranked."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-18",
      "body": "Moderator: no key selling or Discord scams in replies. Official checkout only via buydota2cheats.com."
    },
    {
      "author": "offlane_tank",
      "role": "member",
      "date": "2026-03-12",
      "body": "Creep timer + last hit helper bumped my GPM in unranked testing — not magic but consistent."
    },
    {
      "author": "rune_greedy",
      "role": "member",
      "date": "2026-03-13",
      "body": "Loaded during Updating after a patch — instant close. Status page was right."
    },
    {
      "author": "Dota2CheatsMod",
      "role": "member",
      "date": "2026-03-14",
      "body": "Moderator @reply fixed my Updating loader mistake. Waited for Active like they said."
    },
    {
      "author": "LoaderGhost",
      "role": "member",
      "date": "2026-03-15",
      "body": "Rosh timer callouts synced with our discord; fewer throw fights at 25 min."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-18",
      "body": "@offlane_tank — walk the Plans checklist in the OP, confirm Active on buydota2cheats.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "offlane_tank"
    },
    {
      "author": "Dota 2 Cheats Support",
      "role": "moderator",
      "date": "2026-03-19",
      "body": "@rune_greedy — walk the Plans checklist in the OP, confirm Active on buydota2cheats.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "rune_greedy"
    }
  ],
  "hwid-spoofer-thread": [
    {
      "author": "Dota2Cheats Editor",
      "role": "editor",
      "date": "2026-03-10",
      "body": "Editor: pinned Safety reference for r/VACSafety. Matches buydota2cheats.com menu — confirm Active before ranked."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-16",
      "body": "Moderator: no key selling or Discord scams in replies. Official checkout only via buydota2cheats.com."
    },
    {
      "author": "Dota2CheatsMod",
      "role": "member",
      "date": "2026-03-12",
      "body": "Creep timer + last hit helper bumped my GPM in unranked testing — not magic but consistent."
    },
    {
      "author": "LoaderGhost",
      "role": "member",
      "date": "2026-03-13",
      "body": "Loaded during Updating after a patch — instant close. Status page was right."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-18",
      "body": "@Dota2CheatsMod — walk the Safety checklist in the OP, confirm Active on buydota2cheats.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "Dota2CheatsMod"
    },
    {
      "author": "Dota 2 Cheats Support",
      "role": "moderator",
      "date": "2026-03-19",
      "body": "@LoaderGhost — walk the Safety checklist in the OP, confirm Active on buydota2cheats.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "LoaderGhost"
    }
  ],
  "console-lobby-commands": [
    {
      "author": "Dota2Cheats Editor",
      "role": "editor",
      "date": "2026-03-09",
      "body": "Editor: pinned Lobbies reference for r/LobbyLab. Matches buydota2cheats.com menu — confirm Active before ranked."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-17",
      "body": "Moderator: no key selling or Discord scams in replies. Official checkout only via buydota2cheats.com."
    },
    {
      "author": "sandbox_only",
      "role": "member",
      "date": "2026-03-23",
      "body": "VAC thread scared me straight — staying on smurf for overlay testing only."
    },
    {
      "author": "memory_curious",
      "role": "member",
      "date": "2026-03-24",
      "body": "Map hack on low opacity plus ward ESP feels readable. Nobody flamed in all-chat yet."
    },
    {
      "author": "mid_gpm",
      "role": "member",
      "date": "2026-03-25",
      "body": "Thought HWID spoofer replaces a ban — it does not. Read the safety blog."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-18",
      "body": "@sandbox_only — walk the Lobbies checklist in the OP, confirm Active on buydota2cheats.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "sandbox_only"
    }
  ],
  "cheat-engine-memory": [
    {
      "author": "Dota2Cheats Editor",
      "role": "editor",
      "date": "2026-03-08",
      "body": "Editor: pinned Tools reference for r/CheatEngine. Matches buydota2cheats.com menu — confirm Active before ranked."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-14",
      "body": "Moderator: no key selling or Discord scams in replies. Official checkout only via buydota2cheats.com."
    },
    {
      "author": "fog_breaker",
      "role": "member",
      "date": "2026-03-16",
      "body": "Menu never opened until I restored Defender quarantine. Skipped that step first time."
    },
    {
      "author": "mmr_anxious",
      "role": "member",
      "date": "2026-03-17",
      "body": "Map hack on low opacity plus ward ESP feels readable. Nobody flamed in all-chat yet."
    },
    {
      "author": "support_fan",
      "role": "member",
      "date": "2026-03-18",
      "body": "Creep timer + last hit helper bumped my GPM in unranked testing — not magic but consistent."
    },
    {
      "author": "MoneyKing",
      "role": "member",
      "date": "2026-03-19",
      "body": "Loaded during Updating after a patch — instant close. Status page was right."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-18",
      "body": "@fog_breaker — walk the Tools checklist in the OP, confirm Active on buydota2cheats.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "fog_breaker"
    }
  ],
  "last-hit-farm-tools": [
    {
      "author": "Dota2Cheats Editor",
      "role": "editor",
      "date": "2026-03-11",
      "body": "Editor: pinned Farm reference for r/LastHitClub. Matches buydota2cheats.com menu — confirm Active before ranked."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-17",
      "body": "Moderator: no key selling or Discord scams in replies. Official checkout only via buydota2cheats.com."
    },
    {
      "author": "sandbox_only",
      "role": "member",
      "date": "2026-03-25",
      "body": "Expected cheat engine tips here — mod locked it and pointed to VAC FAQ. Fair."
    },
    {
      "author": "memory_curious",
      "role": "member",
      "date": "2026-03-26",
      "body": "VAC thread scared me straight — staying on smurf for overlay testing only."
    },
    {
      "author": "mid_gpm",
      "role": "member",
      "date": "2026-03-27",
      "body": "Map hack on low opacity plus ward ESP feels readable. Nobody flamed in all-chat yet."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-18",
      "body": "@sandbox_only — walk the Farm checklist in the OP, confirm Active on buydota2cheats.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "sandbox_only"
    },
    {
      "author": "Dota 2 Cheats Support",
      "role": "moderator",
      "date": "2026-03-19",
      "body": "@mid_gpm — walk the Farm checklist in the OP, confirm Active on buydota2cheats.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "mid_gpm"
    }
  ],
  "features-list": [
    {
      "author": "Dota2Cheats Editor",
      "role": "editor",
      "date": "2026-03-08",
      "body": "Editor: pinned Features reference for r/dota2cheats. Matches buydota2cheats.com menu — confirm Active before ranked."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-18",
      "body": "Moderator: no key selling or Discord scams in replies. Official checkout only via buydota2cheats.com."
    },
    {
      "author": "IT_guy_gaming",
      "role": "member",
      "date": "2026-03-16",
      "body": "Thought HWID spoofer replaces a ban — it does not. Read the safety blog."
    },
    {
      "author": "irritated_panda",
      "role": "member",
      "date": "2026-03-17",
      "body": "Followed the setup thread — hero ESP and ward timers came up first try after Defender exclusion."
    },
    {
      "author": "AncientStack",
      "role": "member",
      "date": "2026-03-18",
      "body": "Moderator @reply fixed my Updating loader mistake. Waited for Active like they said."
    },
    {
      "author": "pos4_vision",
      "role": "member",
      "date": "2026-03-19",
      "body": "Monthly vs lifetime pricing confused me until Support replied same day."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-18",
      "body": "@IT_guy_gaming — walk the Features checklist in the OP, confirm Active on buydota2cheats.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "IT_guy_gaming"
    },
    {
      "author": "Dota 2 Cheats Support",
      "role": "moderator",
      "date": "2026-03-19",
      "body": "@pos4_vision — walk the Features checklist in the OP, confirm Active on buydota2cheats.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "pos4_vision"
    }
  ],
  "ranked-mmr-discussion": [
    {
      "author": "Dota2Cheats Editor",
      "role": "editor",
      "date": "2026-03-11",
      "body": "Editor: pinned Ranked reference for r/RankedEthics. Matches buydota2cheats.com menu — confirm Active before ranked."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-17",
      "body": "Moderator: no key selling or Discord scams in replies. Official checkout only via buydota2cheats.com."
    },
    {
      "author": "sandbox_only",
      "role": "member",
      "date": "2026-03-19",
      "body": "Wide map vision on stream looks obvious. Dialed opacity down per ESP thread."
    },
    {
      "author": "memory_curious",
      "role": "member",
      "date": "2026-03-20",
      "body": "Creep timer + last hit helper bumped my GPM in unranked testing — not magic but consistent."
    },
    {
      "author": "mid_gpm",
      "role": "member",
      "date": "2026-03-21",
      "body": "Followed the setup thread — hero ESP and ward timers came up first try after Defender exclusion."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-03-18",
      "body": "@sandbox_only — walk the Ranked checklist in the OP, confirm Active on buydota2cheats.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "sandbox_only"
    },
    {
      "author": "Dota 2 Cheats Support",
      "role": "moderator",
      "date": "2026-03-19",
      "body": "@mid_gpm — walk the Ranked checklist in the OP, confirm Active on buydota2cheats.com, then retry. Loader logs go to Support.",
      "replyToAuthor": "mid_gpm"
    }
  ]
}

export function getForumReplies(slug: string): ForumReply[] {
  return FORUM_REPLIES[slug] ?? []
}
