/** Auto-generated by scripts/generate-dota2-content.mjs */
export type ForumSection = {
  heading: string
  body: string[]
}

export type ForumThread = {
  slug: string
  title: string
  excerpt: string
  metaTitle: string
  metaDescription: string
  searchTerms: string
  date: string
  readMinutes: number
  tag: string
  community: string
  author: string
  score: number
  sections: ForumSection[]
  howTo?: boolean
}

export const FORUM_THREADS: ForumThread[] = [
  {
    "slug": "dota-2-cheats-discussion",
    "title": "Daily thread: dota 2 cheats, map vision, and VAC rumors",
    "excerpt": "Open discussion for dota 2 cheats features, loader status, and whether new patches shifted VAC behavior — read the pinned rules first.",
    "metaTitle": "Daily thread: dota 2 cheats, map vision, and VAC rumors | Dota 2 Cheats Forums",
    "metaDescription": "Open discussion for dota 2 cheats features, loader status, and whether new patches shifted VAC behavior — read the pinned rules first.",
    "searchTerms": "dota 2 cheats,  cheat dota 2",
    "date": "2026-03-05",
    "readMinutes": 6,
    "tag": "General",
    "community": "dota2cheats",
    "author": "AncientStack",
    "score": 973,
    "sections": [
      {
        "heading": "Opening post",
        "body": [
          "Open discussion for dota 2 cheats features, loader status, and whether new patches shifted VAC behavior — read the pinned rules first.",
          "Community: r/dota2cheats · Game: Dota 2 · Anti-cheat: Valve Anti-Cheat (VAC). Official product: buydota2cheats.com."
        ]
      },
      {
        "heading": "Discussion norms",
        "body": [
          "Hero ESP, fog removal, cooldown tracker, creep/rune timers, last-hit helper, ward ESP, roshan timer, and inventory ESP are documented on the features thread.",
          "Moderators may lock threads that share crack links, stolen keys, or Cheat Engine tutorials aimed at live ranked."
        ]
      }
    ]
  },
  {
    "slug": "vac-anticheat-safety",
    "title": "VAC bans after third-party tools — what actually triggers reports?",
    "excerpt": "Valve Anti-Cheat on Dota 2: delayed bans, smurf reports, and why sandbox lobbies are not the same risk as ranked.",
    "metaTitle": "VAC bans after third-party tools — what actually triggers reports? | Dota 2 Cheats Forums",
    "metaDescription": "Valve Anti-Cheat on Dota 2: delayed bans, smurf reports, and why sandbox lobbies are not the same risk as ranked.",
    "searchTerms": "dota 2 cheats,  tf2 anti cheat",
    "date": "2026-03-06",
    "readMinutes": 7,
    "tag": "VAC",
    "community": "VACSafety",
    "author": "mmr_anxious",
    "score": 555,
    "sections": [
      {
        "heading": "Opening post",
        "body": [
          "Valve Anti-Cheat on Dota 2: delayed bans, smurf reports, and why sandbox lobbies are not the same risk as ranked.",
          "Community: r/VACSafety · Game: Dota 2 · Anti-cheat: Valve Anti-Cheat (VAC). Official product: buydota2cheats.com."
        ]
      },
      {
        "heading": "Discussion norms",
        "body": [
          "Hero ESP, fog removal, cooldown tracker, creep/rune timers, last-hit helper, ward ESP, roshan timer, and inventory ESP are documented on the features thread.",
          "Moderators may lock threads that share crack links, stolen keys, or Cheat Engine tutorials aimed at live ranked."
        ]
      }
    ]
  },
  {
    "slug": "complete-setup",
    "title": "Instructions to use Dota 2 Cheats on Windows (loader + first inject)",
    "excerpt": "Step-by-step Dota 2 cheat setup: Active status on buydota2cheats.com, Defender exclusions, Steam launch order, first ESP profile.",
    "metaTitle": "Instructions to use Dota 2 Cheats on Windows (loader + first inject) | Dota 2 Cheats Forums",
    "metaDescription": "Step-by-step Dota 2 cheat setup: Active status on buydota2cheats.com, Defender exclusions, Steam launch order, first ESP profile.",
    "searchTerms": "dota 2 cheats,  get dota 2 cheat",
    "date": "2026-03-07",
    "readMinutes": 8,
    "tag": "Setup",
    "community": "Dota2Setup",
    "author": "support_fan",
    "score": 657,
    "sections": [
      {
        "heading": "1) Check status",
        "body": [
          "Step-by-step Dota 2 cheat setup: Active status on buydota2cheats.com, Defender exclusions, Steam launch order, first ESP profile.",
          "Community: r/Dota2Setup · Game: Dota 2 · Anti-cheat: Valve Anti-Cheat (VAC). Official product: buydota2cheats.com."
        ]
      },
      {
        "heading": "2) Configure modules",
        "body": [
          "Hero ESP, fog removal, cooldown tracker, creep/rune timers, last-hit helper, ward ESP, roshan timer, and inventory ESP are documented on the features thread.",
          "Moderators may lock threads that share crack links, stolen keys, or Cheat Engine tutorials aimed at live ranked."
        ]
      }
    ],
    "howTo": true
  },
  {
    "slug": "hero-esp-config",
    "title": "Hero ESP with items and level — recommended first toggles",
    "excerpt": "Configure hero ESP, item readouts, and level tags without cluttering teamfight vision on Dota 2.",
    "metaTitle": "Hero ESP with items and level — recommended first toggles | Dota 2 Cheats Forums",
    "metaDescription": "Configure hero ESP, item readouts, and level tags without cluttering teamfight vision on Dota 2.",
    "searchTerms": "dota 2 cheats,  cheat dota 2",
    "date": "2026-03-08",
    "readMinutes": 9,
    "tag": "ESP",
    "community": "HeroESP",
    "author": "pos4_vision",
    "score": 584,
    "sections": [
      {
        "heading": "1) Check status",
        "body": [
          "Configure hero ESP, item readouts, and level tags without cluttering teamfight vision on Dota 2.",
          "Community: r/HeroESP · Game: Dota 2 · Anti-cheat: Valve Anti-Cheat (VAC). Official product: buydota2cheats.com."
        ]
      },
      {
        "heading": "2) Configure modules",
        "body": [
          "Hero ESP, fog removal, cooldown tracker, creep/rune timers, last-hit helper, ward ESP, roshan timer, and inventory ESP are documented on the features thread.",
          "Moderators may lock threads that share crack links, stolen keys, or Cheat Engine tutorials aimed at live ranked."
        ]
      }
    ],
    "howTo": true
  },
  {
    "slug": "map-hack-fog-config",
    "title": "Full map hack / fog removal — sane defaults for trios",
    "excerpt": "Remove fog of war responsibly: pair map vision with ward ESP so you still respect true vision mechanics.",
    "metaTitle": "Full map hack / fog removal — sane defaults for trios | Dota 2 Cheats Forums",
    "metaDescription": "Remove fog of war responsibly: pair map vision with ward ESP so you still respect true vision mechanics.",
    "searchTerms": "dota 2 cheats",
    "date": "2026-03-09",
    "readMinutes": 6,
    "tag": "Map",
    "community": "MapVision",
    "author": "fog_breaker",
    "score": 868,
    "sections": [
      {
        "heading": "1) Check status",
        "body": [
          "Remove fog of war responsibly: pair map vision with ward ESP so you still respect true vision mechanics.",
          "Community: r/MapVision · Game: Dota 2 · Anti-cheat: Valve Anti-Cheat (VAC). Official product: buydota2cheats.com."
        ]
      },
      {
        "heading": "2) Configure modules",
        "body": [
          "Hero ESP, fog removal, cooldown tracker, creep/rune timers, last-hit helper, ward ESP, roshan timer, and inventory ESP are documented on the features thread.",
          "Moderators may lock threads that share crack links, stolen keys, or Cheat Engine tutorials aimed at live ranked."
        ]
      }
    ],
    "howTo": true
  },
  {
    "slug": "buy-dota-2-cheats-safely",
    "title": "Buying dota 2 cheats safely — checkout, delivery, and scams",
    "excerpt": "Use only the official checkout URL, verify buydota2cheats.com in the address bar, and ignore random Discord DMs selling keys.",
    "metaTitle": "Buying dota 2 cheats safely — checkout, delivery, and scams | Dota 2 Cheats Forums",
    "metaDescription": "Use only the official checkout URL, verify buydota2cheats.com in the address bar, and ignore random Discord DMs selling keys.",
    "searchTerms": "dota 2 cheats,  buy dota 2 cheats",
    "date": "2026-03-10",
    "readMinutes": 7,
    "tag": "Buying",
    "community": "Dota2Deals",
    "author": "MoneyKing",
    "score": 726,
    "sections": [
      {
        "heading": "Opening post",
        "body": [
          "Use only the official checkout URL, verify buydota2cheats.com in the address bar, and ignore random Discord DMs selling keys.",
          "Community: r/Dota2Deals · Game: Dota 2 · Anti-cheat: Valve Anti-Cheat (VAC). Official product: buydota2cheats.com."
        ]
      },
      {
        "heading": "Discussion norms",
        "body": [
          "Hero ESP, fog removal, cooldown tracker, creep/rune timers, last-hit helper, ward ESP, roshan timer, and inventory ESP are documented on the features thread.",
          "Moderators may lock threads that share crack links, stolen keys, or Cheat Engine tutorials aimed at live ranked."
        ]
      }
    ]
  },
  {
    "slug": "game-patch-status",
    "title": "Patch day: Dota 2 update vs loader Active / Updating",
    "excerpt": "When Valve ships a Dota 2 patch, loader status may flip Updating — queue ranked only after Active returns.",
    "metaTitle": "Patch day: Dota 2 update vs loader Active / Updating | Dota 2 Cheats Forums",
    "metaDescription": "When Valve ships a Dota 2 patch, loader status may flip Updating — queue ranked only after Active returns.",
    "searchTerms": "dota 2 cheats,  dota 2 patch",
    "date": "2026-03-11",
    "readMinutes": 8,
    "tag": "Patches",
    "community": "PatchWatch",
    "author": "patch_day_survivor",
    "score": 250,
    "sections": [
      {
        "heading": "Opening post",
        "body": [
          "When Valve ships a Dota 2 patch, loader status may flip Updating — queue ranked only after Active returns.",
          "Community: r/PatchWatch · Game: Dota 2 · Anti-cheat: Valve Anti-Cheat (VAC). Official product: buydota2cheats.com."
        ]
      },
      {
        "heading": "Discussion norms",
        "body": [
          "Hero ESP, fog removal, cooldown tracker, creep/rune timers, last-hit helper, ward ESP, roshan timer, and inventory ESP are documented on the features thread.",
          "Moderators may lock threads that share crack links, stolen keys, or Cheat Engine tutorials aimed at live ranked."
        ]
      }
    ]
  },
  {
    "slug": "loader-errors",
    "title": "Loader closes instantly / menu never opens — fix checklist",
    "excerpt": "Menu not opening, antivirus quarantine, wrong game build — confirm Active status before tweaking ESP toggles.",
    "metaTitle": "Loader closes instantly / menu never opens — fix checklist | Dota 2 Cheats Forums",
    "metaDescription": "Menu not opening, antivirus quarantine, wrong game build — confirm Active status before tweaking ESP toggles.",
    "searchTerms": "dota 2 cheats",
    "date": "2026-03-12",
    "readMinutes": 9,
    "tag": "Support",
    "community": "LoaderHelp",
    "author": "defender_hater",
    "score": 157,
    "sections": [
      {
        "heading": "1) Check status",
        "body": [
          "Menu not opening, antivirus quarantine, wrong game build — confirm Active status before tweaking ESP toggles.",
          "Community: r/LoaderHelp · Game: Dota 2 · Anti-cheat: Valve Anti-Cheat (VAC). Official product: buydota2cheats.com."
        ]
      },
      {
        "heading": "2) Configure modules",
        "body": [
          "Hero ESP, fog removal, cooldown tracker, creep/rune timers, last-hit helper, ward ESP, roshan timer, and inventory ESP are documented on the features thread.",
          "Moderators may lock threads that share crack links, stolen keys, or Cheat Engine tutorials aimed at live ranked."
        ]
      }
    ],
    "howTo": true
  },
  {
    "slug": "dota-2-cheats-lifetime",
    "title": "Lifetime vs monthly ($150 vs $35) — which plan for you?",
    "excerpt": "Compare monthly (P30D) and lifetime (P99Y) access for Dota 2 Cheats — billing questions go to Support with order email.",
    "metaTitle": "Lifetime vs monthly ($150 vs $35) — which plan for you? | Dota 2 Cheats Forums",
    "metaDescription": "Compare monthly (P30D) and lifetime (P99Y) access for Dota 2 Cheats — billing questions go to Support with order email.",
    "searchTerms": "dota 2 cheats lifetime",
    "date": "2026-03-13",
    "readMinutes": 6,
    "tag": "Plans",
    "community": "Dota2Deals",
    "author": "longterm_core",
    "score": 814,
    "sections": [
      {
        "heading": "Opening post",
        "body": [
          "Compare monthly (P30D) and lifetime (P99Y) access for Dota 2 Cheats — billing questions go to Support with order email.",
          "Community: r/Dota2Deals · Game: Dota 2 · Anti-cheat: Valve Anti-Cheat (VAC). Official product: buydota2cheats.com."
        ]
      },
      {
        "heading": "Discussion norms",
        "body": [
          "Hero ESP, fog removal, cooldown tracker, creep/rune timers, last-hit helper, ward ESP, roshan timer, and inventory ESP are documented on the features thread.",
          "Moderators may lock threads that share crack links, stolen keys, or Cheat Engine tutorials aimed at live ranked."
        ]
      }
    ]
  },
  {
    "slug": "hwid-spoofer-thread",
    "title": "HWID spoofer basics — does it replace safe loader habits?",
    "excerpt": "What HWID spoofers claim to do, why they are not a substitute for conservative settings, and Support boundaries.",
    "metaTitle": "HWID spoofer basics — does it replace safe loader habits? | Dota 2 Cheats Forums",
    "metaDescription": "What HWID spoofers claim to do, why they are not a substitute for conservative settings, and Support boundaries.",
    "searchTerms": "hwid spoofer,  dota 2 cheats",
    "date": "2026-03-14",
    "readMinutes": 7,
    "tag": "Safety",
    "community": "VACSafety",
    "author": "hardware_reset",
    "score": 236,
    "sections": [
      {
        "heading": "Opening post",
        "body": [
          "What HWID spoofers claim to do, why they are not a substitute for conservative settings, and Support boundaries.",
          "Community: r/VACSafety · Game: Dota 2 · Anti-cheat: Valve Anti-Cheat (VAC). Official product: buydota2cheats.com."
        ]
      },
      {
        "heading": "Discussion norms",
        "body": [
          "Hero ESP, fog removal, cooldown tracker, creep/rune timers, last-hit helper, ward ESP, roshan timer, and inventory ESP are documented on the features thread.",
          "Moderators may lock threads that share crack links, stolen keys, or Cheat Engine tutorials aimed at live ranked."
        ]
      }
    ]
  },
  {
    "slug": "console-lobby-commands",
    "title": "cheat dota 2 lobby / dota 2 cheats lobby — custom game setup",
    "excerpt": "Custom lobby cheats for practice: bots, gold, items — not the same as ranked matchmaking overlays.",
    "metaTitle": "cheat dota 2 lobby / dota 2 cheats lobby — custom game setup | Dota 2 Cheats Forums",
    "metaDescription": "Custom lobby cheats for practice: bots, gold, items — not the same as ranked matchmaking overlays.",
    "searchTerms": "cheat dota 2 lobby,  dota 2 cheats lobby,  cheat lobby dota 2",
    "date": "2026-03-15",
    "readMinutes": 8,
    "tag": "Lobbies",
    "community": "LobbyLab",
    "author": "sandbox_only",
    "score": 909,
    "sections": [
      {
        "heading": "Opening post",
        "body": [
          "Custom lobby cheats for practice: bots, gold, items — not the same as ranked matchmaking overlays.",
          "Community: r/LobbyLab · Game: Dota 2 · Anti-cheat: Valve Anti-Cheat (VAC). Official product: buydota2cheats.com."
        ]
      },
      {
        "heading": "Discussion norms",
        "body": [
          "Hero ESP, fog removal, cooldown tracker, creep/rune timers, last-hit helper, ward ESP, roshan timer, and inventory ESP are documented on the features thread.",
          "Moderators may lock threads that share crack links, stolen keys, or Cheat Engine tutorials aimed at live ranked."
        ]
      }
    ]
  },
  {
    "slug": "cheat-engine-memory",
    "title": "cheat engine dota 2 — memory editing risks on VAC",
    "excerpt": "Why Cheat Engine threads get nuked by moderators: VAC scans and ToS violations on live accounts.",
    "metaTitle": "cheat engine dota 2 — memory editing risks on VAC | Dota 2 Cheats Forums",
    "metaDescription": "Why Cheat Engine threads get nuked by moderators: VAC scans and ToS violations on live accounts.",
    "searchTerms": "cheat engine dota 2,  cheat dota 2",
    "date": "2026-03-16",
    "readMinutes": 9,
    "tag": "Tools",
    "community": "CheatEngine",
    "author": "memory_curious",
    "score": 842,
    "sections": [
      {
        "heading": "Opening post",
        "body": [
          "Why Cheat Engine threads get nuked by moderators: VAC scans and ToS violations on live accounts.",
          "Community: r/CheatEngine · Game: Dota 2 · Anti-cheat: Valve Anti-Cheat (VAC). Official product: buydota2cheats.com."
        ]
      },
      {
        "heading": "Discussion norms",
        "body": [
          "Hero ESP, fog removal, cooldown tracker, creep/rune timers, last-hit helper, ward ESP, roshan timer, and inventory ESP are documented on the features thread.",
          "Moderators may lock threads that share crack links, stolen keys, or Cheat Engine tutorials aimed at live ranked."
        ]
      }
    ]
  },
  {
    "slug": "last-hit-farm-tools",
    "title": "Last hit prediction helper + creep timers — lane efficiency",
    "excerpt": "Stack creep spawn timers with last-hit helpers — still need mouse discipline; tools widen timing windows only.",
    "metaTitle": "Last hit prediction helper + creep timers — lane efficiency | Dota 2 Cheats Forums",
    "metaDescription": "Stack creep spawn timers with last-hit helpers — still need mouse discipline; tools widen timing windows only.",
    "searchTerms": "dota 2 cheats,  last hit",
    "date": "2026-03-17",
    "readMinutes": 6,
    "tag": "Farm",
    "community": "LastHitClub",
    "author": "mid_gpm",
    "score": 909,
    "sections": [
      {
        "heading": "Opening post",
        "body": [
          "Stack creep spawn timers with last-hit helpers — still need mouse discipline; tools widen timing windows only.",
          "Community: r/LastHitClub · Game: Dota 2 · Anti-cheat: Valve Anti-Cheat (VAC). Official product: buydota2cheats.com."
        ]
      },
      {
        "heading": "Discussion norms",
        "body": [
          "Hero ESP, fog removal, cooldown tracker, creep/rune timers, last-hit helper, ward ESP, roshan timer, and inventory ESP are documented on the features thread.",
          "Moderators may lock threads that share crack links, stolen keys, or Cheat Engine tutorials aimed at live ranked."
        ]
      }
    ]
  },
  {
    "slug": "features-list",
    "title": "Dota 2 Cheats feature list (ESP, map hack, timers, support)",
    "excerpt": "Official module checklist: hero ESP, fog removal, cooldown tracker, rune/rosh timers, auto-dodge, 24/7 support.",
    "metaTitle": "Dota 2 Cheats feature list (ESP, map hack, timers, support) | Dota 2 Cheats Forums",
    "metaDescription": "Official module checklist: hero ESP, fog removal, cooldown tracker, rune/rosh timers, auto-dodge, 24/7 support.",
    "searchTerms": "dota 2 cheats,  dota 2 hacks",
    "date": "2026-03-18",
    "readMinutes": 7,
    "tag": "Features",
    "community": "dota2cheats",
    "author": "Dota2CheatsMod",
    "score": 838,
    "sections": [
      {
        "heading": "Opening post",
        "body": [
          "Official module checklist: hero ESP, fog removal, cooldown tracker, rune/rosh timers, auto-dodge, 24/7 support.",
          "Community: r/dota2cheats · Game: Dota 2 · Anti-cheat: Valve Anti-Cheat (VAC). Official product: buydota2cheats.com."
        ]
      },
      {
        "heading": "Discussion norms",
        "body": [
          "Hero ESP, fog removal, cooldown tracker, creep/rune timers, last-hit helper, ward ESP, roshan timer, and inventory ESP are documented on the features thread.",
          "Moderators may lock threads that share crack links, stolen keys, or Cheat Engine tutorials aimed at live ranked."
        ]
      }
    ]
  },
  {
    "slug": "ranked-mmr-discussion",
    "title": "Using overlays in ranked — reports, behavior score, smurf risk",
    "excerpt": "Ranked matchmaking plus obvious map vision equals reports. Community norms and why moderators lock flame threads.",
    "metaTitle": "Using overlays in ranked — reports, behavior score, smurf risk | Dota 2 Cheats Forums",
    "metaDescription": "Ranked matchmaking plus obvious map vision equals reports. Community norms and why moderators lock flame threads.",
    "searchTerms": "dota 2 cheats,  cheat dota 2",
    "date": "2026-03-19",
    "readMinutes": 8,
    "tag": "Ranked",
    "community": "RankedEthics",
    "author": "behavior_score_1",
    "score": 669,
    "sections": [
      {
        "heading": "Opening post",
        "body": [
          "Ranked matchmaking plus obvious map vision equals reports. Community norms and why moderators lock flame threads.",
          "Community: r/RankedEthics · Game: Dota 2 · Anti-cheat: Valve Anti-Cheat (VAC). Official product: buydota2cheats.com."
        ]
      },
      {
        "heading": "Discussion norms",
        "body": [
          "Hero ESP, fog removal, cooldown tracker, creep/rune timers, last-hit helper, ward ESP, roshan timer, and inventory ESP are documented on the features thread.",
          "Moderators may lock threads that share crack links, stolen keys, or Cheat Engine tutorials aimed at live ranked."
        ]
      }
    ]
  }
]

export function getForumThread(slug: string) {
  return FORUM_THREADS.find((f) => f.slug === slug)
}

export function getRelatedForumThreads(slug: string, limit = 6): ForumThread[] {
  const current = getForumThread(slug)
  if (!current) return []
  return FORUM_THREADS.filter((f) => f.slug !== slug)
    .sort((a, b) => {
      const tagRank = (p: ForumThread) => (p.tag === current.tag ? 0 : 1)
      return tagRank(a) - tagRank(b) || a.title.localeCompare(b.title)
    })
    .slice(0, limit)
}

export { forumPath } from './blog-paths'
