/** Auto-generated by scripts/generate-isle-forums.mjs */
export type ForumReplyRole = 'editor' | 'moderator' | 'member'

export type ForumReply = {
  author: string
  date: string
  body: string
  role?: ForumReplyRole
  /** When set, this staff post answers a member reply above. */
  replyToAuthor?: string
}

export const FORUM_REPLIES: Record<string, ForumReply[]> = {
  "features-list": [
    {
      "author": "Isle Guides Editor",
      "role": "editor",
      "date": "2026-09-08",
      "body": "Editor: this Features thread is locked read-only. Steps match the live The Isle menu on buyislecheats.com — confirm Active before you queue."
    },
    {
      "author": "IT_guy_gaming",
      "role": "member",
      "date": "2026-09-16",
      "body": "Forced loader while Updating — instant kick. Read status next time lol."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-17",
      "body": "@IT_guy_gaming — loading while status shows Updating will fail every time. Wait until buyislecheats.com lists Active, fully exit the game, then run the loader once. No menu toggles fix a mismatched build.",
      "replyToAuthor": "IT_guy_gaming"
    },
    {
      "author": "defender_hater",
      "role": "member",
      "date": "2026-09-17",
      "body": "Status page said Active, loader matched, ESP came up first try on Win11."
    },
    {
      "author": "Isle Guides Support",
      "role": "moderator",
      "date": "2026-09-19",
      "body": "@defender_hater — Active on the site plus a clean inject path is the baseline. If anything breaks after a game update, recheck status before you change ESP toggles. (Follow-up #2 — still locked; use Support for account-specific issues.)",
      "replyToAuthor": "defender_hater"
    },
    {
      "author": "ridge_runner",
      "role": "member",
      "date": "2026-09-18",
      "body": "Radar range tip fixed my cluttered minimap. Trios rotate cleaner now."
    },
    {
      "author": "Kestrel_09",
      "role": "member",
      "date": "2026-09-19",
      "body": "Skeleton on max brightness looks ridiculous on stream. Muted colors helped."
    },
    {
      "author": "m4rtin.l",
      "role": "member",
      "date": "2026-09-20",
      "body": "Monthly sub updates included so far — patch Tuesday to Thursday Active again."
    }
  ],
  "complete-setup": [
    {
      "author": "Isle Guides Editor",
      "role": "editor",
      "date": "2026-09-11",
      "body": "Editor: this Setup thread is locked read-only. Steps match the live The Isle menu on buyislecheats.com — confirm Active before you queue."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-13",
      "body": "Moderator reminder: if status shows Updating on buyislecheats.com, settings changes here will not fix inject failures — wait for Active."
    },
    {
      "author": "newbie_isle",
      "role": "member",
      "date": "2026-09-13",
      "body": "Forced loader while Updating — instant kick. Read status next time lol."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-14",
      "body": "@newbie_isle — loading while status shows Updating will fail every time. Wait until buyislecheats.com lists Active, fully exit the game, then run the loader once. No menu toggles fix a mismatched build.",
      "replyToAuthor": "newbie_isle"
    },
    {
      "author": "IT_guy_gaming",
      "role": "member",
      "date": "2026-09-14",
      "body": "Status page said Active, loader matched, ESP came up first try on Win11."
    },
    {
      "author": "Isle Guides Support",
      "role": "moderator",
      "date": "2026-09-16",
      "body": "@IT_guy_gaming — Active on the site plus a clean inject path is the baseline. If anything breaks after a game update, recheck status before you change ESP toggles. (Follow-up #2 — still locked; use Support for account-specific issues.)",
      "replyToAuthor": "IT_guy_gaming"
    },
    {
      "author": "defender_hater",
      "role": "member",
      "date": "2026-09-15",
      "body": "Radar range tip fixed my cluttered minimap. Trios rotate cleaner now."
    },
    {
      "author": "ridge_runner",
      "role": "member",
      "date": "2026-09-16",
      "body": "Skeleton on max brightness looks ridiculous on stream. Muted colors helped."
    }
  ],
  "the-isle-cheats-guide": [
    {
      "author": "Isle Guides Editor",
      "role": "editor",
      "date": "2026-09-09",
      "body": "Editor update: \"The Isle Cheats Guide: Safety, Features, and Survival Tips\" was refreshed after the latest patch. Archive only — billing and loader keys go through Support."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-17",
      "body": "Moderator: replies are disabled on archive threads. Share loader logs in Support, not in locked forums."
    },
    {
      "author": "Kestrel_09",
      "role": "member",
      "date": "2026-09-11",
      "body": "Vehicle occupied flag saved us from a bait truck. Worth reading before enabling everything."
    },
    {
      "author": "m4rtin.l",
      "role": "member",
      "date": "2026-09-12",
      "body": "Saved config after first run — second login was two clicks. Wish I did that day one."
    },
    {
      "author": "Isle Guides Support",
      "role": "moderator",
      "date": "2026-09-14",
      "body": "@m4rtin.l — good call saving a profile. Name configs by mode (ESP-only vs full assist) so you are not re-toggling mid-queue when your squad swaps roles. (Follow-up #2 — still locked; use Support for account-specific issues.)",
      "replyToAuthor": "m4rtin.l"
    },
    {
      "author": "softpeek",
      "role": "member",
      "date": "2026-09-13",
      "body": "Wide FOV got me roasted in squad Discord kill cam. Dialed back per guide."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-14",
      "body": "@softpeek — wide FOV plus low smooth reads obvious on kill cam. Cut FOV roughly in half, raise smooth, and keep visible check on — the aimbot section in this thread has sane starting numbers.",
      "replyToAuthor": "softpeek"
    }
  ],
  "the-isle-evrima-cheats-recode": [
    {
      "author": "Isle Guides Editor",
      "role": "editor",
      "date": "2026-09-10",
      "body": "Pinned reference for the isle evrima cheats recode. Do not copy old FOV screenshots from Discord; use the checklist in the opening post."
    },
    {
      "author": "patch_day_survivor",
      "role": "member",
      "date": "2026-09-24",
      "body": "Visible check + low FOV like you said. Nobody typed a word in post-match chat."
    },
    {
      "author": "Isle Guides Support",
      "role": "moderator",
      "date": "2026-09-26",
      "body": "@patch_day_survivor — visible check plus tighter FOV is the usual fix for quiet kill cams. Screenshot your menu once so you can restore the same numbers after patches. (Follow-up #2 — still locked; use Support for account-specific issues.)",
      "replyToAuthor": "patch_day_survivor"
    },
    {
      "author": "filterking",
      "role": "member",
      "date": "2026-09-25",
      "body": "Skipped antivirus step, menu never opened. My fault but frustrating hour wasted."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-26",
      "body": "@filterking — add the delivery folder to Windows Defender exclusions before the first inject, reboot once, and launch from the The Isle main menu only. If Defender quarantined files, restore them from protection history, then retry.",
      "replyToAuthor": "filterking"
    }
  ],
  "advanced-esp-tactics": [
    {
      "author": "Isle Guides Editor",
      "role": "editor",
      "date": "2026-09-13",
      "body": "Pinned reference for advanced esp tactics. Do not copy old FOV screenshots from Discord; use the checklist in the opening post."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-17",
      "body": "Mod note — keep ESP configs conservative in large lobbies. Visible check and distance caps are strongly recommended."
    },
    {
      "author": "newbie_isle",
      "role": "member",
      "date": "2026-09-15",
      "body": "Followed this thread before cranking every toggle — first growth session night actually went smooth."
    },
    {
      "author": "Isle Guides Support",
      "role": "moderator",
      "date": "2026-09-17",
      "body": "@newbie_isle — walk through the ESP checklist in the opening post, confirm Active on buyislecheats.com, then retry with a saved config. If the loader still closes instantly, open Support with a screenshot of your status page. (Follow-up #2 — still locked; use Support for account-specific issues.)",
      "replyToAuthor": "newbie_isle"
    },
    {
      "author": "IT_guy_gaming",
      "role": "member",
      "date": "2026-09-16",
      "body": "Expected magic — still died to a sound flank. ESP does not replace headphones."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-17",
      "body": "@IT_guy_gaming — ESP does not replace audio. Keep radar range moderate and OOF arrows on so you still rotate when someone sprints your blind side.",
      "replyToAuthor": "IT_guy_gaming"
    },
    {
      "author": "defender_hater",
      "role": "member",
      "date": "2026-09-17",
      "body": "Visible check + low FOV like you said. Nobody typed a word in post-match chat."
    },
    {
      "author": "ridge_runner",
      "role": "member",
      "date": "2026-09-18",
      "body": "Vehicle occupied flag saved us from a bait truck. Worth reading before enabling everything."
    }
  ],
  "best-the-isle-cheats-review-2026": [
    {
      "author": "Isle Guides Editor",
      "role": "editor",
      "date": "2026-09-11",
      "body": "Editor: this Review thread is locked read-only. Steps match the live The Isle menu on buyislecheats.com — confirm Active before you queue."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-19",
      "body": "Moderator: replies are disabled on archive threads. Share loader logs in Support, not in locked forums."
    },
    {
      "author": "defender_hater",
      "role": "member",
      "date": "2026-09-25",
      "body": "Skipped antivirus step, menu never opened. My fault but frustrating hour wasted."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-26",
      "body": "@defender_hater — add the delivery folder to Windows Defender exclusions before the first inject, reboot once, and launch from the The Isle main menu only. If Defender quarantined files, restore them from protection history, then retry.",
      "replyToAuthor": "defender_hater"
    },
    {
      "author": "ridge_runner",
      "role": "member",
      "date": "2026-09-26",
      "body": "Visible check + low FOV like you said. Nobody typed a word in post-match chat."
    },
    {
      "author": "Kestrel_09",
      "role": "member",
      "date": "2026-09-27",
      "body": "Vehicle occupied flag saved us from a bait truck. Worth reading before enabling everything."
    },
    {
      "author": "m4rtin.l",
      "role": "member",
      "date": "2026-09-10",
      "body": "Wide FOV got me roasted in squad Discord kill cam. Dialed back per guide."
    },
    {
      "author": "softpeek",
      "role": "member",
      "date": "2026-09-11",
      "body": "Saved config after first run — second login was two clicks. Wish I did that day one."
    },
    {
      "author": "ViktorNorth",
      "role": "member",
      "date": "2026-09-12",
      "body": "Status page said Active, loader matched, ESP came up first try on Win11."
    },
    {
      "author": "Isle Guides Support",
      "role": "moderator",
      "date": "2026-09-14",
      "body": "@ViktorNorth — Active on the site plus a clean inject path is the baseline. If anything breaks after a game update, recheck status before you change ESP toggles. (Follow-up #2 — still locked; use Support for account-specific issues.)",
      "replyToAuthor": "ViktorNorth"
    }
  ],
  "hwid-spoofer-safety": [
    {
      "author": "Isle Guides Editor",
      "role": "editor",
      "date": "2026-09-12",
      "body": "Editor update: \"Discover What an HWID Spoofer Does for Safety\" was refreshed after the latest patch. Archive only — billing and loader keys go through Support."
    },
    {
      "author": "capslock_warrior",
      "role": "member",
      "date": "2026-09-26",
      "body": "Radar range tip fixed my cluttered minimap. Trios rotate cleaner now."
    },
    {
      "author": "newbie_isle",
      "role": "member",
      "date": "2026-09-27",
      "body": "Monthly sub updates included so far — patch Tuesday to Thursday Active again."
    },
    {
      "author": "Isle Guides Support",
      "role": "moderator",
      "date": "2026-09-28",
      "body": "@newbie_isle — subscription builds track patch days; when status flips Updating, pause ranked-style queues until Active returns instead of forcing the loader. (Follow-up #2 — still locked; use Support for account-specific issues.)",
      "replyToAuthor": "newbie_isle"
    },
    {
      "author": "IT_guy_gaming",
      "role": "member",
      "date": "2026-09-10",
      "body": "Skeleton on max brightness looks ridiculous on stream. Muted colors helped."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-11",
      "body": "@IT_guy_gaming — drop skeleton opacity and switch to a muted color. Box + distance alone are enough for most trios; neon skeletons are what teammates notice on clips.",
      "replyToAuthor": "IT_guy_gaming"
    }
  ],
  "buy-the-isle-cheats-safely": [
    {
      "author": "Isle Guides Editor",
      "role": "editor",
      "date": "2026-09-12",
      "body": "Editor update: \"Where to Buy The Isle Cheats Safely: Plans and Delivery\" was refreshed after the latest patch. Archive only — billing and loader keys go through Support."
    },
    {
      "author": "ridge_runner",
      "role": "member",
      "date": "2026-09-20",
      "body": "Visible check + low FOV like you said. Nobody typed a word in post-match chat."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-21",
      "body": "@ridge_runner — visible check plus tighter FOV is the usual fix for quiet kill cams. Screenshot your menu once so you can restore the same numbers after patches.",
      "replyToAuthor": "ridge_runner"
    },
    {
      "author": "Kestrel_09",
      "role": "member",
      "date": "2026-09-21",
      "body": "Vehicle occupied flag saved us from a bait truck. Worth reading before enabling everything."
    },
    {
      "author": "Isle Guides Support",
      "role": "moderator",
      "date": "2026-09-23",
      "body": "@Kestrel_09 — occupied/empty flags are hints, not guarantees. Slow peek or have a teammate hard cover before you commit to a truck push. (Follow-up #2 — still locked; use Support for account-specific issues.)",
      "replyToAuthor": "Kestrel_09"
    }
  ],
  "the-isle-cheats-lifetime": [
    {
      "author": "Isle Guides Editor",
      "role": "editor",
      "date": "2026-09-12",
      "body": "Editor update: \"The Isle Cheats Lifetime License: Is Permanent Access Worth It?\" was refreshed after the latest patch. Archive only — billing and loader keys go through Support."
    },
    {
      "author": "ViktorNorth",
      "role": "member",
      "date": "2026-09-14",
      "body": "Radar range tip fixed my cluttered minimap. Trios rotate cleaner now."
    },
    {
      "author": "ghostloot",
      "role": "member",
      "date": "2026-09-15",
      "body": "Monthly sub updates included so far — patch Tuesday to Thursday Active again."
    },
    {
      "author": "PMC_walker",
      "role": "member",
      "date": "2026-09-16",
      "body": "Skeleton on max brightness looks ridiculous on stream. Muted colors helped."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-17",
      "body": "@PMC_walker — drop skeleton opacity and switch to a muted color. Box + distance alone are enough for most trios; neon skeletons are what teammates notice on clips.",
      "replyToAuthor": "PMC_walker"
    },
    {
      "author": "duo_six",
      "role": "member",
      "date": "2026-09-17",
      "body": "Followed this thread before cranking every toggle — first growth session night actually went smooth."
    },
    {
      "author": "Isle Guides Support",
      "role": "moderator",
      "date": "2026-09-19",
      "body": "@duo_six — walk through the Pricing checklist in the opening post, confirm Active on buyislecheats.com, then retry with a saved config. If the loader still closes instantly, open Support with a screenshot of your status page. (Follow-up #2 — still locked; use Support for account-specific issues.)",
      "replyToAuthor": "duo_six"
    },
    {
      "author": "LenaIsle",
      "role": "member",
      "date": "2026-09-18",
      "body": "Visible check + low FOV like you said. Nobody typed a word in post-match chat."
    },
    {
      "author": "impatient_one",
      "role": "member",
      "date": "2026-09-19",
      "body": "Prices on lifetime vs monthly confused me until support replied — doc could be clearer."
    }
  ],
  "player-esp-first": [
    {
      "author": "Isle Guides Editor",
      "role": "editor",
      "date": "2026-09-13",
      "body": "Pinned reference for player esp first. Do not copy old FOV screenshots from Discord; use the checklist in the opening post."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-13",
      "body": "Mod note — keep ESP configs conservative in large lobbies. Visible check and distance caps are strongly recommended."
    },
    {
      "author": "ghostloot",
      "role": "member",
      "date": "2026-09-27",
      "body": "Saved config after first run — second login was two clicks. Wish I did that day one."
    },
    {
      "author": "Isle Guides Support",
      "role": "moderator",
      "date": "2026-09-28",
      "body": "@ghostloot — good call saving a profile. Name configs by mode (ESP-only vs full assist) so you are not re-toggling mid-queue when your squad swaps roles. (Follow-up #2 — still locked; use Support for account-specific issues.)",
      "replyToAuthor": "ghostloot"
    },
    {
      "author": "PMC_walker",
      "role": "member",
      "date": "2026-09-10",
      "body": "Thought vehicle ESP would show loot inside — it does not, just the truck."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-11",
      "body": "@PMC_walker — vehicle ESP shows transports and occupied state, not crate loot inside. Use player ESP and radar for pushes; treat empty vehicle markers as bait until you line-of-sight the hull.",
      "replyToAuthor": "PMC_walker"
    }
  ],
  "silent-aim-overview": [
    {
      "author": "Isle Guides Editor",
      "role": "editor",
      "date": "2026-09-13",
      "body": "Pinned reference for silent aim overview. Do not copy old FOV screenshots from Discord; use the checklist in the opening post."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-13",
      "body": "Mod note — keep Combat configs conservative in large lobbies. Visible check and distance caps are strongly recommended."
    },
    {
      "author": "Kestrel_09",
      "role": "member",
      "date": "2026-09-15",
      "body": "Radar range tip fixed my cluttered minimap. Trios rotate cleaner now."
    },
    {
      "author": "m4rtin.l",
      "role": "member",
      "date": "2026-09-16",
      "body": "Skeleton on max brightness looks ridiculous on stream. Muted colors helped."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-17",
      "body": "@m4rtin.l — drop skeleton opacity and switch to a muted color. Box + distance alone are enough for most trios; neon skeletons are what teammates notice on clips.",
      "replyToAuthor": "m4rtin.l"
    },
    {
      "author": "softpeek",
      "role": "member",
      "date": "2026-09-17",
      "body": "Monthly sub updates included so far — patch Tuesday to Thursday Active again."
    },
    {
      "author": "Isle Guides Support",
      "role": "moderator",
      "date": "2026-09-19",
      "body": "@softpeek — subscription builds track patch days; when status flips Updating, pause ranked-style queues until Active returns instead of forcing the loader. (Follow-up #2 — still locked; use Support for account-specific issues.)",
      "replyToAuthor": "softpeek"
    }
  ],
  "game-patch-status": [
    {
      "author": "Isle Guides Editor",
      "role": "editor",
      "date": "2026-09-08",
      "body": "Editor: this Status thread is locked read-only. Steps match the live The Isle menu on buyislecheats.com — confirm Active before you queue."
    },
    {
      "author": "patch_day_survivor",
      "role": "member",
      "date": "2026-09-10",
      "body": "Expected magic — still died to a sound flank. ESP does not replace headphones."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-11",
      "body": "@patch_day_survivor — ESP does not replace audio. Keep radar range moderate and OOF arrows on so you still rotate when someone sprints your blind side.",
      "replyToAuthor": "patch_day_survivor"
    },
    {
      "author": "filterking",
      "role": "member",
      "date": "2026-09-11",
      "body": "Followed this thread before cranking every toggle — first growth session night actually went smooth."
    },
    {
      "author": "Isle Guides Support",
      "role": "moderator",
      "date": "2026-09-13",
      "body": "@filterking — walk through the Status checklist in the opening post, confirm Active on buyislecheats.com, then retry with a saved config. If the loader still closes instantly, open Support with a screenshot of your status page. (Follow-up #2 — still locked; use Support for account-specific issues.)",
      "replyToAuthor": "filterking"
    }
  ],
  "windows-setup": [
    {
      "author": "Isle Guides Editor",
      "role": "editor",
      "date": "2026-09-11",
      "body": "Editor: this Windows thread is locked read-only. Steps match the live The Isle menu on buyislecheats.com — confirm Active before you queue."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-15",
      "body": "Moderator: replies are disabled on archive threads. Share loader logs in Support, not in locked forums."
    },
    {
      "author": "irritated_panda",
      "role": "member",
      "date": "2026-09-13",
      "body": "Expected magic — still died to a sound flank. ESP does not replace headphones."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-14",
      "body": "@irritated_panda — ESP does not replace audio. Keep radar range moderate and OOF arrows on so you still rotate when someone sprints your blind side.",
      "replyToAuthor": "irritated_panda"
    },
    {
      "author": "capslock_warrior",
      "role": "member",
      "date": "2026-09-14",
      "body": "Followed this thread before cranking every toggle — first growth session night actually went smooth."
    },
    {
      "author": "Isle Guides Support",
      "role": "moderator",
      "date": "2026-09-16",
      "body": "@capslock_warrior — walk through the Windows checklist in the opening post, confirm Active on buyislecheats.com, then retry with a saved config. If the loader still closes instantly, open Support with a screenshot of your status page. (Follow-up #2 — still locked; use Support for account-specific issues.)",
      "replyToAuthor": "capslock_warrior"
    }
  ],
  "disable-antivirus": [
    {
      "author": "Isle Guides Editor",
      "role": "editor",
      "date": "2026-09-10",
      "body": "Pinned reference for disable antivirus. Do not copy old FOV screenshots from Discord; use the checklist in the opening post."
    },
    {
      "author": "IT_guy_gaming",
      "role": "member",
      "date": "2026-09-24",
      "body": "Monthly sub updates included so far — patch Tuesday to Thursday Active again."
    },
    {
      "author": "defender_hater",
      "role": "member",
      "date": "2026-09-25",
      "body": "Prices on lifetime vs monthly confused me until support replied — doc could be clearer."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-26",
      "body": "@defender_hater — start monthly if you play casually; lifetime makes sense when you queue multiple nights a week. Billing questions go to Support with your order email, not this locked thread.",
      "replyToAuthor": "defender_hater"
    },
    {
      "author": "ridge_runner",
      "role": "member",
      "date": "2026-09-26",
      "body": "Followed this thread before cranking every toggle — first growth session night actually went smooth."
    },
    {
      "author": "Isle Guides Support",
      "role": "moderator",
      "date": "2026-09-28",
      "body": "@ridge_runner — walk through the Antivirus checklist in the opening post, confirm Active on buyislecheats.com, then retry with a saved config. If the loader still closes instantly, open Support with a screenshot of your status page. (Follow-up #2 — still locked; use Support for account-specific issues.)",
      "replyToAuthor": "ridge_runner"
    },
    {
      "author": "Kestrel_09",
      "role": "member",
      "date": "2026-09-27",
      "body": "Visible check + low FOV like you said. Nobody typed a word in post-match chat."
    },
    {
      "author": "m4rtin.l",
      "role": "member",
      "date": "2026-09-10",
      "body": "Expected magic — still died to a sound flank. ESP does not replace headphones."
    }
  ],
  "hotkeys": [
    {
      "author": "Isle Guides Editor",
      "role": "editor",
      "date": "2026-09-11",
      "body": "Editor: this Hotkeys thread is locked read-only. Steps match the live The Isle menu on buyislecheats.com — confirm Active before you queue."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-13",
      "body": "Moderator reminder: if status shows Updating on buyislecheats.com, settings changes here will not fix inject failures — wait for Active."
    },
    {
      "author": "solo_q_isle",
      "role": "member",
      "date": "2026-09-25",
      "body": "Skeleton on max brightness looks ridiculous on stream. Muted colors helped."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-26",
      "body": "@solo_q_isle — drop skeleton opacity and switch to a muted color. Box + distance alone are enough for most trios; neon skeletons are what teammates notice on clips.",
      "replyToAuthor": "solo_q_isle"
    },
    {
      "author": "MoneyKing",
      "role": "member",
      "date": "2026-09-26",
      "body": "Radar range tip fixed my cluttered minimap. Trios rotate cleaner now."
    },
    {
      "author": "irritated_panda",
      "role": "member",
      "date": "2026-09-27",
      "body": "Monthly sub updates included so far — patch Tuesday to Thursday Active again."
    },
    {
      "author": "capslock_warrior",
      "role": "member",
      "date": "2026-09-10",
      "body": "Prices on lifetime vs monthly confused me until support replied — doc could be clearer."
    },
    {
      "author": "Isle Guides Support",
      "role": "moderator",
      "date": "2026-09-12",
      "body": "@capslock_warrior — start monthly if you play casually; lifetime makes sense when you queue multiple nights a week. Billing questions go to Support with your order email, not this locked thread. (Follow-up #2 — still locked; use Support for account-specific issues.)",
      "replyToAuthor": "capslock_warrior"
    },
    {
      "author": "newbie_isle",
      "role": "member",
      "date": "2026-09-11",
      "body": "Followed this thread before cranking every toggle — first growth session night actually went smooth."
    }
  ],
  "loader-errors": [
    {
      "author": "Isle Guides Editor",
      "role": "editor",
      "date": "2026-09-11",
      "body": "Editor: this Support thread is locked read-only. Steps match the live The Isle menu on buyislecheats.com — confirm Active before you queue."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-17",
      "body": "Moderator reminder: if status shows Updating on buyislecheats.com, settings changes here will not fix inject failures — wait for Active."
    },
    {
      "author": "newbie_isle",
      "role": "member",
      "date": "2026-09-13",
      "body": "Skeleton on max brightness looks ridiculous on stream. Muted colors helped."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-14",
      "body": "@newbie_isle — drop skeleton opacity and switch to a muted color. Box + distance alone are enough for most trios; neon skeletons are what teammates notice on clips.",
      "replyToAuthor": "newbie_isle"
    },
    {
      "author": "IT_guy_gaming",
      "role": "member",
      "date": "2026-09-14",
      "body": "Radar range tip fixed my cluttered minimap. Trios rotate cleaner now."
    },
    {
      "author": "defender_hater",
      "role": "member",
      "date": "2026-09-15",
      "body": "Monthly sub updates included so far — patch Tuesday to Thursday Active again."
    },
    {
      "author": "Isle Guides Support",
      "role": "moderator",
      "date": "2026-09-17",
      "body": "@defender_hater — subscription builds track patch days; when status flips Updating, pause ranked-style queues until Active returns instead of forcing the loader. (Follow-up #2 — still locked; use Support for account-specific issues.)",
      "replyToAuthor": "defender_hater"
    },
    {
      "author": "ridge_runner",
      "role": "member",
      "date": "2026-09-16",
      "body": "Prices on lifetime vs monthly confused me until support replied — doc could be clearer."
    }
  ],
  "load-status-checklist": [
    {
      "author": "Isle Guides Editor",
      "role": "editor",
      "date": "2026-09-08",
      "body": "Editor: this Status thread is locked read-only. Steps match the live The Isle menu on buyislecheats.com — confirm Active before you queue."
    },
    {
      "author": "m4rtin.l",
      "role": "member",
      "date": "2026-09-22",
      "body": "Skeleton on max brightness looks ridiculous on stream. Muted colors helped."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-23",
      "body": "@m4rtin.l — drop skeleton opacity and switch to a muted color. Box + distance alone are enough for most trios; neon skeletons are what teammates notice on clips.",
      "replyToAuthor": "m4rtin.l"
    },
    {
      "author": "softpeek",
      "role": "member",
      "date": "2026-09-23",
      "body": "Radar range tip fixed my cluttered minimap. Trios rotate cleaner now."
    },
    {
      "author": "ViktorNorth",
      "role": "member",
      "date": "2026-09-24",
      "body": "Monthly sub updates included so far — patch Tuesday to Thursday Active again."
    },
    {
      "author": "Isle Guides Support",
      "role": "moderator",
      "date": "2026-09-26",
      "body": "@ViktorNorth — subscription builds track patch days; when status flips Updating, pause ranked-style queues until Active returns instead of forcing the loader. (Follow-up #2 — still locked; use Support for account-specific issues.)",
      "replyToAuthor": "ViktorNorth"
    },
    {
      "author": "ghostloot",
      "role": "member",
      "date": "2026-09-25",
      "body": "Prices on lifetime vs monthly confused me until support replied — doc could be clearer."
    }
  ],
  "complete-visual-options-breakdown": [
    {
      "author": "Isle Guides Editor",
      "role": "editor",
      "date": "2026-09-13",
      "body": "Pinned reference for complete visual options breakdown. Do not copy old FOV screenshots from Discord; use the checklist in the opening post."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-13",
      "body": "Mod note — keep Visuals configs conservative in large lobbies. Visible check and distance caps are strongly recommended."
    },
    {
      "author": "impatient_one",
      "role": "member",
      "date": "2026-09-21",
      "body": "Vehicle occupied flag saved us from a bait truck. Worth reading before enabling everything."
    },
    {
      "author": "Isle Guides Support",
      "role": "moderator",
      "date": "2026-09-23",
      "body": "@impatient_one — occupied/empty flags are hints, not guarantees. Slow peek or have a teammate hard cover before you commit to a truck push. (Follow-up #2 — still locked; use Support for account-specific issues.)",
      "replyToAuthor": "impatient_one"
    },
    {
      "author": "patch_day_survivor",
      "role": "member",
      "date": "2026-09-22",
      "body": "Wide FOV got me roasted in squad Discord kill cam. Dialed back per guide."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-23",
      "body": "@patch_day_survivor — wide FOV plus low smooth reads obvious on kill cam. Cut FOV roughly in half, raise smooth, and keep visible check on — the aimbot section in this thread has sane starting numbers.",
      "replyToAuthor": "patch_day_survivor"
    },
    {
      "author": "filterking",
      "role": "member",
      "date": "2026-09-23",
      "body": "Saved config after first run — second login was two clicks. Wish I did that day one."
    },
    {
      "author": "twitch_isle",
      "role": "member",
      "date": "2026-09-24",
      "body": "Status page said Active, loader matched, ESP came up first try on Win11."
    },
    {
      "author": "solo_q_isle",
      "role": "member",
      "date": "2026-09-25",
      "body": "Thought vehicle ESP would show loot inside — it does not, just the truck."
    },
    {
      "author": "MoneyKing",
      "role": "member",
      "date": "2026-09-26",
      "body": "Radar range tip fixed my cluttered minimap. Trios rotate cleaner now."
    }
  ],
  "player-esp-tracking": [
    {
      "author": "Isle Guides Editor",
      "role": "editor",
      "date": "2026-09-08",
      "body": "Editor: this ESP thread is locked read-only. Steps match the live The Isle menu on buyislecheats.com — confirm Active before you queue."
    },
    {
      "author": "MoneyKing",
      "role": "member",
      "date": "2026-09-22",
      "body": "Thought vehicle ESP would show loot inside — it does not, just the truck."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-23",
      "body": "@MoneyKing — vehicle ESP shows transports and occupied state, not crate loot inside. Use player ESP and radar for pushes; treat empty vehicle markers as bait until you line-of-sight the hull.",
      "replyToAuthor": "MoneyKing"
    },
    {
      "author": "irritated_panda",
      "role": "member",
      "date": "2026-09-23",
      "body": "Saved config after first run — second login was two clicks. Wish I did that day one."
    },
    {
      "author": "Isle Guides Support",
      "role": "moderator",
      "date": "2026-09-25",
      "body": "@irritated_panda — good call saving a profile. Name configs by mode (ESP-only vs full assist) so you are not re-toggling mid-queue when your squad swaps roles. (Follow-up #2 — still locked; use Support for account-specific issues.)",
      "replyToAuthor": "irritated_panda"
    },
    {
      "author": "capslock_warrior",
      "role": "member",
      "date": "2026-09-24",
      "body": "Status page said Active, loader matched, ESP came up first try on Win11."
    },
    {
      "author": "newbie_isle",
      "role": "member",
      "date": "2026-09-25",
      "body": "Forced loader while Updating — instant kick. Read status next time lol."
    },
    {
      "author": "IT_guy_gaming",
      "role": "member",
      "date": "2026-09-26",
      "body": "Radar range tip fixed my cluttered minimap. Trios rotate cleaner now."
    },
    {
      "author": "defender_hater",
      "role": "member",
      "date": "2026-09-27",
      "body": "Monthly sub updates included so far — patch Tuesday to Thursday Active again."
    }
  ],
  "npc-esp-guide": [
    {
      "author": "Isle Guides Editor",
      "role": "editor",
      "date": "2026-09-09",
      "body": "Editor update: \"NPC ESP Guide: Locating AI Dinosaurs Quickly\" was refreshed after the latest patch. Archive only — billing and loader keys go through Support."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-17",
      "body": "Moderator: replies are disabled on archive threads. Share loader logs in Support, not in locked forums."
    },
    {
      "author": "solo_q_isle",
      "role": "member",
      "date": "2026-09-11",
      "body": "Vehicle occupied flag saved us from a bait truck. Worth reading before enabling everything."
    },
    {
      "author": "Isle Guides Support",
      "role": "moderator",
      "date": "2026-09-13",
      "body": "@solo_q_isle — occupied/empty flags are hints, not guarantees. Slow peek or have a teammate hard cover before you commit to a truck push. (Follow-up #2 — still locked; use Support for account-specific issues.)",
      "replyToAuthor": "solo_q_isle"
    },
    {
      "author": "MoneyKing",
      "role": "member",
      "date": "2026-09-12",
      "body": "Saved config after first run — second login was two clicks. Wish I did that day one."
    },
    {
      "author": "irritated_panda",
      "role": "member",
      "date": "2026-09-13",
      "body": "Wide FOV got me roasted in squad Discord kill cam. Dialed back per guide."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-14",
      "body": "@irritated_panda — wide FOV plus low smooth reads obvious on kill cam. Cut FOV roughly in half, raise smooth, and keep visible check on — the aimbot section in this thread has sane starting numbers.",
      "replyToAuthor": "irritated_panda"
    },
    {
      "author": "capslock_warrior",
      "role": "member",
      "date": "2026-09-14",
      "body": "Status page said Active, loader matched, ESP came up first try on Win11."
    },
    {
      "author": "newbie_isle",
      "role": "member",
      "date": "2026-09-15",
      "body": "Radar range tip fixed my cluttered minimap. Trios rotate cleaner now."
    }
  ],
  "animal-esp-features": [
    {
      "author": "Isle Guides Editor",
      "role": "editor",
      "date": "2026-09-11",
      "body": "Editor: this ESP thread is locked read-only. Steps match the live The Isle menu on buyislecheats.com — confirm Active before you queue."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-13",
      "body": "Moderator reminder: if status shows Updating on buyislecheats.com, settings changes here will not fix inject failures — wait for Active."
    },
    {
      "author": "Kestrel_09",
      "role": "member",
      "date": "2026-09-25",
      "body": "Wide FOV got me roasted in squad Discord kill cam. Dialed back per guide."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-26",
      "body": "@Kestrel_09 — wide FOV plus low smooth reads obvious on kill cam. Cut FOV roughly in half, raise smooth, and keep visible check on — the aimbot section in this thread has sane starting numbers.",
      "replyToAuthor": "Kestrel_09"
    },
    {
      "author": "m4rtin.l",
      "role": "member",
      "date": "2026-09-26",
      "body": "Vehicle occupied flag saved us from a bait truck. Worth reading before enabling everything."
    },
    {
      "author": "softpeek",
      "role": "member",
      "date": "2026-09-27",
      "body": "Saved config after first run — second login was two clicks. Wish I did that day one."
    },
    {
      "author": "Isle Guides Support",
      "role": "moderator",
      "date": "2026-09-28",
      "body": "@softpeek — good call saving a profile. Name configs by mode (ESP-only vs full assist) so you are not re-toggling mid-queue when your squad swaps roles. (Follow-up #2 — still locked; use Support for account-specific issues.)",
      "replyToAuthor": "softpeek"
    }
  ],
  "box-esp-overlays": [
    {
      "author": "Isle Guides Editor",
      "role": "editor",
      "date": "2026-09-12",
      "body": "Editor update: \"Box ESP Overlays for Clear Target Distances\" was refreshed after the latest patch. Archive only — billing and loader keys go through Support."
    },
    {
      "author": "ridge_runner",
      "role": "member",
      "date": "2026-09-26",
      "body": "Radar range tip fixed my cluttered minimap. Trios rotate cleaner now."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-27",
      "body": "@ridge_runner — if the minimap still feels busy, shorten radar range for urban pushes and widen it only when you hold open ground between zones.",
      "replyToAuthor": "ridge_runner"
    },
    {
      "author": "Kestrel_09",
      "role": "member",
      "date": "2026-09-27",
      "body": "Monthly sub updates included so far — patch Tuesday to Thursday Active again."
    },
    {
      "author": "Isle Guides Support",
      "role": "moderator",
      "date": "2026-09-28",
      "body": "@Kestrel_09 — subscription builds track patch days; when status flips Updating, pause ranked-style queues until Active returns instead of forcing the loader. (Follow-up #2 — still locked; use Support for account-specific issues.)",
      "replyToAuthor": "Kestrel_09"
    }
  ],
  "snapline-overlays": [
    {
      "author": "Isle Guides Editor",
      "role": "editor",
      "date": "2026-09-08",
      "body": "Editor: this Visuals thread is locked read-only. Steps match the live The Isle menu on buyislecheats.com — confirm Active before you queue."
    },
    {
      "author": "PMC_walker",
      "role": "member",
      "date": "2026-09-10",
      "body": "Prices on lifetime vs monthly confused me until support replied — doc could be clearer."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-11",
      "body": "@PMC_walker — start monthly if you play casually; lifetime makes sense when you queue multiple nights a week. Billing questions go to Support with your order email, not this locked thread.",
      "replyToAuthor": "PMC_walker"
    },
    {
      "author": "duo_six",
      "role": "member",
      "date": "2026-09-11",
      "body": "Monthly sub updates included so far — patch Tuesday to Thursday Active again."
    },
    {
      "author": "Isle Guides Support",
      "role": "moderator",
      "date": "2026-09-13",
      "body": "@duo_six — subscription builds track patch days; when status flips Updating, pause ranked-style queues until Active returns instead of forcing the loader. (Follow-up #2 — still locked; use Support for account-specific issues.)",
      "replyToAuthor": "duo_six"
    },
    {
      "author": "LenaIsle",
      "role": "member",
      "date": "2026-09-12",
      "body": "Followed this thread before cranking every toggle — first growth session night actually went smooth."
    }
  ],
  "player-name-tags": [
    {
      "author": "Isle Guides Editor",
      "role": "editor",
      "date": "2026-09-13",
      "body": "Pinned reference for player name tags. Do not copy old FOV screenshots from Discord; use the checklist in the opening post."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-19",
      "body": "Moderator reminder: if status shows Updating on buyislecheats.com, settings changes here will not fix inject failures — wait for Active."
    },
    {
      "author": "filterking",
      "role": "member",
      "date": "2026-09-21",
      "body": "Visible check + low FOV like you said. Nobody typed a word in post-match chat."
    },
    {
      "author": "twitch_isle",
      "role": "member",
      "date": "2026-09-22",
      "body": "Skipped antivirus step, menu never opened. My fault but frustrating hour wasted."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-23",
      "body": "@twitch_isle — add the delivery folder to Windows Defender exclusions before the first inject, reboot once, and launch from the The Isle main menu only. If Defender quarantined files, restore them from protection history, then retry.",
      "replyToAuthor": "twitch_isle"
    },
    {
      "author": "solo_q_isle",
      "role": "member",
      "date": "2026-09-23",
      "body": "Vehicle occupied flag saved us from a bait truck. Worth reading before enabling everything."
    },
    {
      "author": "Isle Guides Support",
      "role": "moderator",
      "date": "2026-09-25",
      "body": "@solo_q_isle — occupied/empty flags are hints, not guarantees. Slow peek or have a teammate hard cover before you commit to a truck push. (Follow-up #2 — still locked; use Support for account-specific issues.)",
      "replyToAuthor": "solo_q_isle"
    }
  ],
  "distance-indicators": [
    {
      "author": "Isle Guides Editor",
      "role": "editor",
      "date": "2026-09-10",
      "body": "Pinned reference for distance indicators. Do not copy old FOV screenshots from Discord; use the checklist in the opening post."
    },
    {
      "author": "capslock_warrior",
      "role": "member",
      "date": "2026-09-18",
      "body": "Monthly sub updates included so far — patch Tuesday to Thursday Active again."
    },
    {
      "author": "newbie_isle",
      "role": "member",
      "date": "2026-09-19",
      "body": "Prices on lifetime vs monthly confused me until support replied — doc could be clearer."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-20",
      "body": "@newbie_isle — start monthly if you play casually; lifetime makes sense when you queue multiple nights a week. Billing questions go to Support with your order email, not this locked thread.",
      "replyToAuthor": "newbie_isle"
    },
    {
      "author": "IT_guy_gaming",
      "role": "member",
      "date": "2026-09-20",
      "body": "Followed this thread before cranking every toggle — first growth session night actually went smooth."
    },
    {
      "author": "Isle Guides Support",
      "role": "moderator",
      "date": "2026-09-22",
      "body": "@IT_guy_gaming — walk through the Visuals checklist in the opening post, confirm Active on buyislecheats.com, then retry with a saved config. If the loader still closes instantly, open Support with a screenshot of your status page. (Follow-up #2 — still locked; use Support for account-specific issues.)",
      "replyToAuthor": "IT_guy_gaming"
    }
  ],
  "corpse-esp": [
    {
      "author": "Isle Guides Editor",
      "role": "editor",
      "date": "2026-09-13",
      "body": "Pinned reference for corpse esp. Do not copy old FOV screenshots from Discord; use the checklist in the opening post."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-13",
      "body": "Mod note — keep Visuals configs conservative in large lobbies. Visible check and distance caps are strongly recommended."
    },
    {
      "author": "ghostloot",
      "role": "member",
      "date": "2026-09-15",
      "body": "Monthly sub updates included so far — patch Tuesday to Thursday Active again."
    },
    {
      "author": "Isle Guides Support",
      "role": "moderator",
      "date": "2026-09-17",
      "body": "@ghostloot — subscription builds track patch days; when status flips Updating, pause ranked-style queues until Active returns instead of forcing the loader. (Follow-up #2 — still locked; use Support for account-specific issues.)",
      "replyToAuthor": "ghostloot"
    },
    {
      "author": "PMC_walker",
      "role": "member",
      "date": "2026-09-16",
      "body": "Prices on lifetime vs monthly confused me until support replied — doc could be clearer."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-17",
      "body": "@PMC_walker — start monthly if you play casually; lifetime makes sense when you queue multiple nights a week. Billing questions go to Support with your order email, not this locked thread.",
      "replyToAuthor": "PMC_walker"
    }
  ],
  "health-tracking-overlays": [
    {
      "author": "Isle Guides Editor",
      "role": "editor",
      "date": "2026-09-10",
      "body": "Pinned reference for health tracking overlays. Do not copy old FOV screenshots from Discord; use the checklist in the opening post."
    },
    {
      "author": "twitch_isle",
      "role": "member",
      "date": "2026-09-12",
      "body": "Vehicle occupied flag saved us from a bait truck. Worth reading before enabling everything."
    },
    {
      "author": "solo_q_isle",
      "role": "member",
      "date": "2026-09-13",
      "body": "Wide FOV got me roasted in squad Discord kill cam. Dialed back per guide."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-14",
      "body": "@solo_q_isle — wide FOV plus low smooth reads obvious on kill cam. Cut FOV roughly in half, raise smooth, and keep visible check on — the aimbot section in this thread has sane starting numbers.",
      "replyToAuthor": "solo_q_isle"
    },
    {
      "author": "MoneyKing",
      "role": "member",
      "date": "2026-09-14",
      "body": "Saved config after first run — second login was two clicks. Wish I did that day one."
    },
    {
      "author": "Isle Guides Support",
      "role": "moderator",
      "date": "2026-09-16",
      "body": "@MoneyKing — good call saving a profile. Name configs by mode (ESP-only vs full assist) so you are not re-toggling mid-queue when your squad swaps roles. (Follow-up #2 — still locked; use Support for account-specific issues.)",
      "replyToAuthor": "MoneyKing"
    },
    {
      "author": "irritated_panda",
      "role": "member",
      "date": "2026-09-15",
      "body": "Status page said Active, loader matched, ESP came up first try on Win11."
    }
  ],
  "stamina-status-display": [
    {
      "author": "Isle Guides Editor",
      "role": "editor",
      "date": "2026-09-09",
      "body": "Editor update: \"Stamina Status Display for Predator Pursuits\" was refreshed after the latest patch. Archive only — billing and loader keys go through Support."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-17",
      "body": "Moderator: replies are disabled on archive threads. Share loader logs in Support, not in locked forums."
    },
    {
      "author": "newbie_isle",
      "role": "member",
      "date": "2026-09-23",
      "body": "Visible check + low FOV like you said. Nobody typed a word in post-match chat."
    },
    {
      "author": "IT_guy_gaming",
      "role": "member",
      "date": "2026-09-24",
      "body": "Vehicle occupied flag saved us from a bait truck. Worth reading before enabling everything."
    },
    {
      "author": "Isle Guides Support",
      "role": "moderator",
      "date": "2026-09-26",
      "body": "@IT_guy_gaming — occupied/empty flags are hints, not guarantees. Slow peek or have a teammate hard cover before you commit to a truck push. (Follow-up #2 — still locked; use Support for account-specific issues.)",
      "replyToAuthor": "IT_guy_gaming"
    },
    {
      "author": "defender_hater",
      "role": "member",
      "date": "2026-09-25",
      "body": "Skipped antivirus step, menu never opened. My fault but frustrating hour wasted."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-26",
      "body": "@defender_hater — add the delivery folder to Windows Defender exclusions before the first inject, reboot once, and launch from the The Isle main menu only. If Defender quarantined files, restore them from protection history, then retry.",
      "replyToAuthor": "defender_hater"
    },
    {
      "author": "ridge_runner",
      "role": "member",
      "date": "2026-09-26",
      "body": "Saved config after first run — second login was two clicks. Wish I did that day one."
    }
  ],
  "growth-tracker": [
    {
      "author": "Isle Guides Editor",
      "role": "editor",
      "date": "2026-09-08",
      "body": "Editor: this Visuals thread is locked read-only. Steps match the live The Isle menu on buyislecheats.com — confirm Active before you queue."
    },
    {
      "author": "MoneyKing",
      "role": "member",
      "date": "2026-09-22",
      "body": "Forced loader while Updating — instant kick. Read status next time lol."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-23",
      "body": "@MoneyKing — loading while status shows Updating will fail every time. Wait until buyislecheats.com lists Active, fully exit the game, then run the loader once. No menu toggles fix a mismatched build.",
      "replyToAuthor": "MoneyKing"
    },
    {
      "author": "irritated_panda",
      "role": "member",
      "date": "2026-09-23",
      "body": "Status page said Active, loader matched, ESP came up first try on Win11."
    },
    {
      "author": "capslock_warrior",
      "role": "member",
      "date": "2026-09-24",
      "body": "Radar range tip fixed my cluttered minimap. Trios rotate cleaner now."
    },
    {
      "author": "newbie_isle",
      "role": "member",
      "date": "2026-09-25",
      "body": "Skeleton on max brightness looks ridiculous on stream. Muted colors helped."
    },
    {
      "author": "IT_guy_gaming",
      "role": "member",
      "date": "2026-09-26",
      "body": "Monthly sub updates included so far — patch Tuesday to Thursday Active again."
    },
    {
      "author": "defender_hater",
      "role": "member",
      "date": "2026-09-27",
      "body": "Followed this thread before cranking every toggle — first growth session night actually went smooth."
    },
    {
      "author": "Isle Guides Support",
      "role": "moderator",
      "date": "2026-09-28",
      "body": "@defender_hater — walk through the Visuals checklist in the opening post, confirm Active on buyislecheats.com, then retry with a saved config. If the loader still closes instantly, open Support with a screenshot of your status page. (Follow-up #2 — still locked; use Support for account-specific issues.)",
      "replyToAuthor": "defender_hater"
    }
  ],
  "species-identification-esp": [
    {
      "author": "Isle Guides Editor",
      "role": "editor",
      "date": "2026-09-12",
      "body": "Editor update: \"Species Identification ESP: Know Your Threat Level\" was refreshed after the latest patch. Archive only — billing and loader keys go through Support."
    },
    {
      "author": "twitch_isle",
      "role": "member",
      "date": "2026-09-20",
      "body": "Followed this thread before cranking every toggle — first growth session night actually went smooth."
    },
    {
      "author": "Isle Guides Support",
      "role": "moderator",
      "date": "2026-09-22",
      "body": "@twitch_isle — walk through the Visuals checklist in the opening post, confirm Active on buyislecheats.com, then retry with a saved config. If the loader still closes instantly, open Support with a screenshot of your status page. (Follow-up #2 — still locked; use Support for account-specific issues.)",
      "replyToAuthor": "twitch_isle"
    },
    {
      "author": "solo_q_isle",
      "role": "member",
      "date": "2026-09-21",
      "body": "Visible check + low FOV like you said. Nobody typed a word in post-match chat."
    },
    {
      "author": "MoneyKing",
      "role": "member",
      "date": "2026-09-22",
      "body": "Expected magic — still died to a sound flank. ESP does not replace headphones."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-23",
      "body": "@MoneyKing — ESP does not replace audio. Keep radar range moderate and OOF arrows on so you still rotate when someone sprints your blind side.",
      "replyToAuthor": "MoneyKing"
    },
    {
      "author": "irritated_panda",
      "role": "member",
      "date": "2026-09-23",
      "body": "Vehicle occupied flag saved us from a bait truck. Worth reading before enabling everything."
    }
  ],
  "player-direction-indicators": [
    {
      "author": "Isle Guides Editor",
      "role": "editor",
      "date": "2026-09-12",
      "body": "Editor update: \"Player Direction Indicators to Anticipate Flanks\" was refreshed after the latest patch. Archive only — billing and loader keys go through Support."
    },
    {
      "author": "IT_guy_gaming",
      "role": "member",
      "date": "2026-09-14",
      "body": "Monthly sub updates included so far — patch Tuesday to Thursday Active again."
    },
    {
      "author": "defender_hater",
      "role": "member",
      "date": "2026-09-15",
      "body": "Followed this thread before cranking every toggle — first growth session night actually went smooth."
    },
    {
      "author": "ridge_runner",
      "role": "member",
      "date": "2026-09-16",
      "body": "Prices on lifetime vs monthly confused me until support replied — doc could be clearer."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-17",
      "body": "@ridge_runner — start monthly if you play casually; lifetime makes sense when you queue multiple nights a week. Billing questions go to Support with your order email, not this locked thread.",
      "replyToAuthor": "ridge_runner"
    },
    {
      "author": "Kestrel_09",
      "role": "member",
      "date": "2026-09-17",
      "body": "Visible check + low FOV like you said. Nobody typed a word in post-match chat."
    },
    {
      "author": "m4rtin.l",
      "role": "member",
      "date": "2026-09-18",
      "body": "Vehicle occupied flag saved us from a bait truck. Worth reading before enabling everything."
    },
    {
      "author": "Isle Guides Support",
      "role": "moderator",
      "date": "2026-09-20",
      "body": "@m4rtin.l — occupied/empty flags are hints, not guarantees. Slow peek or have a teammate hard cover before you commit to a truck push. (Follow-up #2 — still locked; use Support for account-specific issues.)",
      "replyToAuthor": "m4rtin.l"
    }
  ],
  "head-dot-precision": [
    {
      "author": "Isle Guides Editor",
      "role": "editor",
      "date": "2026-09-13",
      "body": "Pinned reference for head dot precision. Do not copy old FOV screenshots from Discord; use the checklist in the opening post."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-17",
      "body": "Mod note — keep Visuals configs conservative in large lobbies. Visible check and distance caps are strongly recommended."
    },
    {
      "author": "impatient_one",
      "role": "member",
      "date": "2026-09-15",
      "body": "Radar range tip fixed my cluttered minimap. Trios rotate cleaner now."
    },
    {
      "author": "patch_day_survivor",
      "role": "member",
      "date": "2026-09-16",
      "body": "Skeleton on max brightness looks ridiculous on stream. Muted colors helped."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-17",
      "body": "@patch_day_survivor — drop skeleton opacity and switch to a muted color. Box + distance alone are enough for most trios; neon skeletons are what teammates notice on clips.",
      "replyToAuthor": "patch_day_survivor"
    },
    {
      "author": "filterking",
      "role": "member",
      "date": "2026-09-17",
      "body": "Monthly sub updates included so far — patch Tuesday to Thursday Active again."
    },
    {
      "author": "twitch_isle",
      "role": "member",
      "date": "2026-09-18",
      "body": "Followed this thread before cranking every toggle — first growth session night actually went smooth."
    },
    {
      "author": "Isle Guides Support",
      "role": "moderator",
      "date": "2026-09-20",
      "body": "@twitch_isle — walk through the Visuals checklist in the opening post, confirm Active on buyislecheats.com, then retry with a saved config. If the loader still closes instantly, open Support with a screenshot of your status page. (Follow-up #2 — still locked; use Support for account-specific issues.)",
      "replyToAuthor": "twitch_isle"
    },
    {
      "author": "solo_q_isle",
      "role": "member",
      "date": "2026-09-19",
      "body": "Prices on lifetime vs monthly confused me until support replied — doc could be clearer."
    },
    {
      "author": "MoneyKing",
      "role": "member",
      "date": "2026-09-20",
      "body": "Visible check + low FOV like you said. Nobody typed a word in post-match chat."
    }
  ],
  "visible-check-settings": [
    {
      "author": "Isle Guides Editor",
      "role": "editor",
      "date": "2026-09-09",
      "body": "Editor update: \"Visible Check Settings to Avoid Wall Detection Issues\" was refreshed after the latest patch. Archive only — billing and loader keys go through Support."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-15",
      "body": "Mod note — keep Visuals configs conservative in large lobbies. Visible check and distance caps are strongly recommended."
    },
    {
      "author": "defender_hater",
      "role": "member",
      "date": "2026-09-17",
      "body": "Saved config after first run — second login was two clicks. Wish I did that day one."
    },
    {
      "author": "ridge_runner",
      "role": "member",
      "date": "2026-09-18",
      "body": "Status page said Active, loader matched, ESP came up first try on Win11."
    },
    {
      "author": "Isle Guides Support",
      "role": "moderator",
      "date": "2026-09-20",
      "body": "@ridge_runner — Active on the site plus a clean inject path is the baseline. If anything breaks after a game update, recheck status before you change ESP toggles. (Follow-up #2 — still locked; use Support for account-specific issues.)",
      "replyToAuthor": "ridge_runner"
    },
    {
      "author": "Kestrel_09",
      "role": "member",
      "date": "2026-09-19",
      "body": "Thought vehicle ESP would show loot inside — it does not, just the truck."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-20",
      "body": "@Kestrel_09 — vehicle ESP shows transports and occupied state, not crate loot inside. Use player ESP and radar for pushes; treat empty vehicle markers as bait until you line-of-sight the hull.",
      "replyToAuthor": "Kestrel_09"
    },
    {
      "author": "m4rtin.l",
      "role": "member",
      "date": "2026-09-20",
      "body": "Radar range tip fixed my cluttered minimap. Trios rotate cleaner now."
    },
    {
      "author": "softpeek",
      "role": "member",
      "date": "2026-09-21",
      "body": "Monthly sub updates included so far — patch Tuesday to Thursday Active again."
    },
    {
      "author": "ViktorNorth",
      "role": "member",
      "date": "2026-09-22",
      "body": "Forced loader while Updating — instant kick. Read status next time lol."
    }
  ],
  "gore-visual-options": [
    {
      "author": "Isle Guides Editor",
      "role": "editor",
      "date": "2026-09-11",
      "body": "Editor: this Visuals thread is locked read-only. Steps match the live The Isle menu on buyislecheats.com — confirm Active before you queue."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-15",
      "body": "Moderator: replies are disabled on archive threads. Share loader logs in Support, not in locked forums."
    },
    {
      "author": "defender_hater",
      "role": "member",
      "date": "2026-09-13",
      "body": "Forced loader while Updating — instant kick. Read status next time lol."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-14",
      "body": "@defender_hater — loading while status shows Updating will fail every time. Wait until buyislecheats.com lists Active, fully exit the game, then run the loader once. No menu toggles fix a mismatched build.",
      "replyToAuthor": "defender_hater"
    },
    {
      "author": "ridge_runner",
      "role": "member",
      "date": "2026-09-14",
      "body": "Status page said Active, loader matched, ESP came up first try on Win11."
    },
    {
      "author": "Kestrel_09",
      "role": "member",
      "date": "2026-09-15",
      "body": "Radar range tip fixed my cluttered minimap. Trios rotate cleaner now."
    },
    {
      "author": "Isle Guides Support",
      "role": "moderator",
      "date": "2026-09-17",
      "body": "@Kestrel_09 — if the minimap still feels busy, shorten radar range for urban pushes and widen it only when you hold open ground between zones. (Follow-up #2 — still locked; use Support for account-specific issues.)",
      "replyToAuthor": "Kestrel_09"
    },
    {
      "author": "m4rtin.l",
      "role": "member",
      "date": "2026-09-16",
      "body": "Skeleton on max brightness looks ridiculous on stream. Muted colors helped."
    },
    {
      "author": "softpeek",
      "role": "member",
      "date": "2026-09-17",
      "body": "Monthly sub updates included so far — patch Tuesday to Thursday Active again."
    },
    {
      "author": "ViktorNorth",
      "role": "member",
      "date": "2026-09-18",
      "body": "Followed this thread before cranking every toggle — first growth session night actually went smooth."
    }
  ],
  "fruit-esp": [
    {
      "author": "Isle Guides Editor",
      "role": "editor",
      "date": "2026-09-13",
      "body": "Pinned reference for fruit esp. Do not copy old FOV screenshots from Discord; use the checklist in the opening post."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-13",
      "body": "Mod note — keep Visuals configs conservative in large lobbies. Visible check and distance caps are strongly recommended."
    },
    {
      "author": "newbie_isle",
      "role": "member",
      "date": "2026-09-15",
      "body": "Followed this thread before cranking every toggle — first growth session night actually went smooth."
    },
    {
      "author": "IT_guy_gaming",
      "role": "member",
      "date": "2026-09-16",
      "body": "Expected magic — still died to a sound flank. ESP does not replace headphones."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-17",
      "body": "@IT_guy_gaming — ESP does not replace audio. Keep radar range moderate and OOF arrows on so you still rotate when someone sprints your blind side.",
      "replyToAuthor": "IT_guy_gaming"
    },
    {
      "author": "defender_hater",
      "role": "member",
      "date": "2026-09-17",
      "body": "Visible check + low FOV like you said. Nobody typed a word in post-match chat."
    },
    {
      "author": "ridge_runner",
      "role": "member",
      "date": "2026-09-18",
      "body": "Vehicle occupied flag saved us from a bait truck. Worth reading before enabling everything."
    },
    {
      "author": "Isle Guides Support",
      "role": "moderator",
      "date": "2026-09-20",
      "body": "@ridge_runner — occupied/empty flags are hints, not guarantees. Slow peek or have a teammate hard cover before you commit to a truck push. (Follow-up #2 — still locked; use Support for account-specific issues.)",
      "replyToAuthor": "ridge_runner"
    }
  ],
  "water-source-esp": [
    {
      "author": "Isle Guides Editor",
      "role": "editor",
      "date": "2026-09-08",
      "body": "Editor: this Visuals thread is locked read-only. Steps match the live The Isle menu on buyislecheats.com — confirm Active before you queue."
    },
    {
      "author": "patch_day_survivor",
      "role": "member",
      "date": "2026-09-10",
      "body": "Forced loader while Updating — instant kick. Read status next time lol."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-11",
      "body": "@patch_day_survivor — loading while status shows Updating will fail every time. Wait until buyislecheats.com lists Active, fully exit the game, then run the loader once. No menu toggles fix a mismatched build.",
      "replyToAuthor": "patch_day_survivor"
    },
    {
      "author": "filterking",
      "role": "member",
      "date": "2026-09-11",
      "body": "Status page said Active, loader matched, ESP came up first try on Win11."
    },
    {
      "author": "Isle Guides Support",
      "role": "moderator",
      "date": "2026-09-13",
      "body": "@filterking — Active on the site plus a clean inject path is the baseline. If anything breaks after a game update, recheck status before you change ESP toggles. (Follow-up #2 — still locked; use Support for account-specific issues.)",
      "replyToAuthor": "filterking"
    }
  ],
  "optimizing-max-distance-filters": [
    {
      "author": "Isle Guides Editor",
      "role": "editor",
      "date": "2026-09-09",
      "body": "Editor update: \"Optimizing Max Distance Filters to Clear Your HUD\" was refreshed after the latest patch. Archive only — billing and loader keys go through Support."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-19",
      "body": "Mod note — keep Visuals configs conservative in large lobbies. Visible check and distance caps are strongly recommended."
    },
    {
      "author": "defender_hater",
      "role": "member",
      "date": "2026-09-23",
      "body": "Followed this thread before cranking every toggle — first growth session night actually went smooth."
    },
    {
      "author": "ridge_runner",
      "role": "member",
      "date": "2026-09-24",
      "body": "Visible check + low FOV like you said. Nobody typed a word in post-match chat."
    },
    {
      "author": "Kestrel_09",
      "role": "member",
      "date": "2026-09-25",
      "body": "Expected magic — still died to a sound flank. ESP does not replace headphones."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-26",
      "body": "@Kestrel_09 — ESP does not replace audio. Keep radar range moderate and OOF arrows on so you still rotate when someone sprints your blind side.",
      "replyToAuthor": "Kestrel_09"
    },
    {
      "author": "m4rtin.l",
      "role": "member",
      "date": "2026-09-26",
      "body": "Vehicle occupied flag saved us from a bait truck. Worth reading before enabling everything."
    },
    {
      "author": "softpeek",
      "role": "member",
      "date": "2026-09-27",
      "body": "Saved config after first run — second login was two clicks. Wish I did that day one."
    },
    {
      "author": "Isle Guides Support",
      "role": "moderator",
      "date": "2026-09-28",
      "body": "@softpeek — good call saving a profile. Name configs by mode (ESP-only vs full assist) so you are not re-toggling mid-queue when your squad swaps roles. (Follow-up #2 — still locked; use Support for account-specific issues.)",
      "replyToAuthor": "softpeek"
    },
    {
      "author": "ViktorNorth",
      "role": "member",
      "date": "2026-09-10",
      "body": "Skipped antivirus step, menu never opened. My fault but frustrating hour wasted."
    }
  ],
  "miscellaneous-utility-settings": [
    {
      "author": "Isle Guides Editor",
      "role": "editor",
      "date": "2026-09-09",
      "body": "Editor update: \"Miscellaneous Utility Settings for Optimized Gameplay\" was refreshed after the latest patch. Archive only — billing and loader keys go through Support."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-15",
      "body": "Mod note — keep Misc configs conservative in large lobbies. Visible check and distance caps are strongly recommended."
    },
    {
      "author": "irritated_panda",
      "role": "member",
      "date": "2026-09-11",
      "body": "Followed this thread before cranking every toggle — first growth session night actually went smooth."
    },
    {
      "author": "Isle Guides Support",
      "role": "moderator",
      "date": "2026-09-13",
      "body": "@irritated_panda — walk through the Misc checklist in the opening post, confirm Active on buyislecheats.com, then retry with a saved config. If the loader still closes instantly, open Support with a screenshot of your status page. (Follow-up #2 — still locked; use Support for account-specific issues.)",
      "replyToAuthor": "irritated_panda"
    },
    {
      "author": "capslock_warrior",
      "role": "member",
      "date": "2026-09-12",
      "body": "Visible check + low FOV like you said. Nobody typed a word in post-match chat."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-13",
      "body": "@capslock_warrior — visible check plus tighter FOV is the usual fix for quiet kill cams. Screenshot your menu once so you can restore the same numbers after patches.",
      "replyToAuthor": "capslock_warrior"
    }
  ],
  "custom-crosshair-overlays": [
    {
      "author": "Isle Guides Editor",
      "role": "editor",
      "date": "2026-09-08",
      "body": "Editor: this Misc thread is locked read-only. Steps match the live The Isle menu on buyislecheats.com — confirm Active before you queue."
    },
    {
      "author": "patch_day_survivor",
      "role": "member",
      "date": "2026-09-22",
      "body": "Skeleton on max brightness looks ridiculous on stream. Muted colors helped."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-23",
      "body": "@patch_day_survivor — drop skeleton opacity and switch to a muted color. Box + distance alone are enough for most trios; neon skeletons are what teammates notice on clips.",
      "replyToAuthor": "patch_day_survivor"
    },
    {
      "author": "filterking",
      "role": "member",
      "date": "2026-09-23",
      "body": "Radar range tip fixed my cluttered minimap. Trios rotate cleaner now."
    },
    {
      "author": "Isle Guides Support",
      "role": "moderator",
      "date": "2026-09-25",
      "body": "@filterking — if the minimap still feels busy, shorten radar range for urban pushes and widen it only when you hold open ground between zones. (Follow-up #2 — still locked; use Support for account-specific issues.)",
      "replyToAuthor": "filterking"
    }
  ],
  "quick-suicide-command": [
    {
      "author": "Isle Guides Editor",
      "role": "editor",
      "date": "2026-09-08",
      "body": "Editor: this Misc thread is locked read-only. Steps match the live The Isle menu on buyislecheats.com — confirm Active before you queue."
    },
    {
      "author": "ViktorNorth",
      "role": "member",
      "date": "2026-09-22",
      "body": "Thought vehicle ESP would show loot inside — it does not, just the truck."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-23",
      "body": "@ViktorNorth — vehicle ESP shows transports and occupied state, not crate loot inside. Use player ESP and radar for pushes; treat empty vehicle markers as bait until you line-of-sight the hull.",
      "replyToAuthor": "ViktorNorth"
    },
    {
      "author": "ghostloot",
      "role": "member",
      "date": "2026-09-23",
      "body": "Saved config after first run — second login was two clicks. Wish I did that day one."
    },
    {
      "author": "PMC_walker",
      "role": "member",
      "date": "2026-09-24",
      "body": "Status page said Active, loader matched, ESP came up first try on Win11."
    },
    {
      "author": "duo_six",
      "role": "member",
      "date": "2026-09-25",
      "body": "Forced loader while Updating — instant kick. Read status next time lol."
    },
    {
      "author": "Isle Guides Support",
      "role": "moderator",
      "date": "2026-09-27",
      "body": "@duo_six — loading while status shows Updating will fail every time. Wait until buyislecheats.com lists Active, fully exit the game, then run the loader once. No menu toggles fix a mismatched build. (Follow-up #2 — still locked; use Support for account-specific issues.)",
      "replyToAuthor": "duo_six"
    },
    {
      "author": "LenaIsle",
      "role": "member",
      "date": "2026-09-26",
      "body": "Radar range tip fixed my cluttered minimap. Trios rotate cleaner now."
    },
    {
      "author": "impatient_one",
      "role": "member",
      "date": "2026-09-27",
      "body": "Monthly sub updates included so far — patch Tuesday to Thursday Active again."
    }
  ],
  "fullbright-visuals": [
    {
      "author": "Isle Guides Editor",
      "role": "editor",
      "date": "2026-09-11",
      "body": "Editor: this Misc thread is locked read-only. Steps match the live The Isle menu on buyislecheats.com — confirm Active before you queue."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-19",
      "body": "Moderator: replies are disabled on archive threads. Share loader logs in Support, not in locked forums."
    },
    {
      "author": "softpeek",
      "role": "member",
      "date": "2026-09-19",
      "body": "Wide FOV got me roasted in squad Discord kill cam. Dialed back per guide."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-20",
      "body": "@softpeek — wide FOV plus low smooth reads obvious on kill cam. Cut FOV roughly in half, raise smooth, and keep visible check on — the aimbot section in this thread has sane starting numbers.",
      "replyToAuthor": "softpeek"
    },
    {
      "author": "ViktorNorth",
      "role": "member",
      "date": "2026-09-20",
      "body": "Vehicle occupied flag saved us from a bait truck. Worth reading before enabling everything."
    },
    {
      "author": "Isle Guides Support",
      "role": "moderator",
      "date": "2026-09-22",
      "body": "@ViktorNorth — occupied/empty flags are hints, not guarantees. Slow peek or have a teammate hard cover before you commit to a truck push. (Follow-up #2 — still locked; use Support for account-specific issues.)",
      "replyToAuthor": "ViktorNorth"
    },
    {
      "author": "ghostloot",
      "role": "member",
      "date": "2026-09-21",
      "body": "Saved config after first run — second login was two clicks. Wish I did that day one."
    },
    {
      "author": "PMC_walker",
      "role": "member",
      "date": "2026-09-22",
      "body": "Thought vehicle ESP would show loot inside — it does not, just the truck."
    },
    {
      "author": "duo_six",
      "role": "member",
      "date": "2026-09-23",
      "body": "Status page said Active, loader matched, ESP came up first try on Win11."
    }
  ],
  "performance-monitoring-fps": [
    {
      "author": "Isle Guides Editor",
      "role": "editor",
      "date": "2026-09-09",
      "body": "Editor update: \"Performance Monitoring: Displaying FPS In-Game\" was refreshed after the latest patch. Archive only — billing and loader keys go through Support."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-13",
      "body": "Moderator: replies are disabled on archive threads. Share loader logs in Support, not in locked forums."
    },
    {
      "author": "newbie_isle",
      "role": "member",
      "date": "2026-09-17",
      "body": "Radar range tip fixed my cluttered minimap. Trios rotate cleaner now."
    },
    {
      "author": "Isle Guides Support",
      "role": "moderator",
      "date": "2026-09-19",
      "body": "@newbie_isle — if the minimap still feels busy, shorten radar range for urban pushes and widen it only when you hold open ground between zones. (Follow-up #2 — still locked; use Support for account-specific issues.)",
      "replyToAuthor": "newbie_isle"
    },
    {
      "author": "IT_guy_gaming",
      "role": "member",
      "date": "2026-09-18",
      "body": "Monthly sub updates included so far — patch Tuesday to Thursday Active again."
    },
    {
      "author": "defender_hater",
      "role": "member",
      "date": "2026-09-19",
      "body": "Skeleton on max brightness looks ridiculous on stream. Muted colors helped."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-20",
      "body": "@defender_hater — drop skeleton opacity and switch to a muted color. Box + distance alone are enough for most trios; neon skeletons are what teammates notice on clips.",
      "replyToAuthor": "defender_hater"
    },
    {
      "author": "ridge_runner",
      "role": "member",
      "date": "2026-09-20",
      "body": "Followed this thread before cranking every toggle — first growth session night actually went smooth."
    }
  ],
  "resolution-display-tool": [
    {
      "author": "Isle Guides Editor",
      "role": "editor",
      "date": "2026-09-12",
      "body": "Editor update: \"Resolution Display Tool for Custom Overlays\" was refreshed after the latest patch. Archive only — billing and loader keys go through Support."
    },
    {
      "author": "ridge_runner",
      "role": "member",
      "date": "2026-09-14",
      "body": "Followed this thread before cranking every toggle — first growth session night actually went smooth."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-15",
      "body": "@ridge_runner — walk through the Misc checklist in the opening post, confirm Active on buyislecheats.com, then retry with a saved config. If the loader still closes instantly, open Support with a screenshot of your status page.",
      "replyToAuthor": "ridge_runner"
    },
    {
      "author": "Kestrel_09",
      "role": "member",
      "date": "2026-09-15",
      "body": "Visible check + low FOV like you said. Nobody typed a word in post-match chat."
    },
    {
      "author": "Isle Guides Support",
      "role": "moderator",
      "date": "2026-09-17",
      "body": "@Kestrel_09 — visible check plus tighter FOV is the usual fix for quiet kill cams. Screenshot your menu once so you can restore the same numbers after patches. (Follow-up #2 — still locked; use Support for account-specific issues.)",
      "replyToAuthor": "Kestrel_09"
    }
  ],
  "in-game-time-display": [
    {
      "author": "Isle Guides Editor",
      "role": "editor",
      "date": "2026-09-11",
      "body": "Editor: this Misc thread is locked read-only. Steps match the live The Isle menu on buyislecheats.com — confirm Active before you queue."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-17",
      "body": "Moderator reminder: if status shows Updating on buyislecheats.com, settings changes here will not fix inject failures — wait for Active."
    },
    {
      "author": "impatient_one",
      "role": "member",
      "date": "2026-09-25",
      "body": "Wide FOV got me roasted in squad Discord kill cam. Dialed back per guide."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-26",
      "body": "@impatient_one — wide FOV plus low smooth reads obvious on kill cam. Cut FOV roughly in half, raise smooth, and keep visible check on — the aimbot section in this thread has sane starting numbers.",
      "replyToAuthor": "impatient_one"
    },
    {
      "author": "patch_day_survivor",
      "role": "member",
      "date": "2026-09-26",
      "body": "Vehicle occupied flag saved us from a bait truck. Worth reading before enabling everything."
    },
    {
      "author": "filterking",
      "role": "member",
      "date": "2026-09-27",
      "body": "Saved config after first run — second login was two clicks. Wish I did that day one."
    },
    {
      "author": "twitch_isle",
      "role": "member",
      "date": "2026-09-10",
      "body": "Thought vehicle ESP would show loot inside — it does not, just the truck."
    },
    {
      "author": "solo_q_isle",
      "role": "member",
      "date": "2026-09-11",
      "body": "Status page said Active, loader matched, ESP came up first try on Win11."
    },
    {
      "author": "Isle Guides Support",
      "role": "moderator",
      "date": "2026-09-13",
      "body": "@solo_q_isle — Active on the site plus a clean inject path is the baseline. If anything breaks after a game update, recheck status before you change ESP toggles. (Follow-up #2 — still locked; use Support for account-specific issues.)",
      "replyToAuthor": "solo_q_isle"
    },
    {
      "author": "MoneyKing",
      "role": "member",
      "date": "2026-09-12",
      "body": "Radar range tip fixed my cluttered minimap. Trios rotate cleaner now."
    }
  ],
  "custom-menu-hotkey": [
    {
      "author": "Isle Guides Editor",
      "role": "editor",
      "date": "2026-09-12",
      "body": "Editor update: \"Setting Up Your Custom Menu Hotkey for Quick Toggles\" was refreshed after the latest patch. Archive only — billing and loader keys go through Support."
    },
    {
      "author": "ridge_runner",
      "role": "member",
      "date": "2026-09-14",
      "body": "Visible check + low FOV like you said. Nobody typed a word in post-match chat."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-15",
      "body": "@ridge_runner — visible check plus tighter FOV is the usual fix for quiet kill cams. Screenshot your menu once so you can restore the same numbers after patches.",
      "replyToAuthor": "ridge_runner"
    },
    {
      "author": "Kestrel_09",
      "role": "member",
      "date": "2026-09-15",
      "body": "Vehicle occupied flag saved us from a bait truck. Worth reading before enabling everything."
    },
    {
      "author": "Isle Guides Support",
      "role": "moderator",
      "date": "2026-09-17",
      "body": "@Kestrel_09 — occupied/empty flags are hints, not guarantees. Slow peek or have a teammate hard cover before you commit to a truck push. (Follow-up #2 — still locked; use Support for account-specific issues.)",
      "replyToAuthor": "Kestrel_09"
    }
  ],
  "panic-key-configuration": [
    {
      "author": "Isle Guides Editor",
      "role": "editor",
      "date": "2026-09-10",
      "body": "Pinned reference for panic key configuration. Do not copy old FOV screenshots from Discord; use the checklist in the opening post."
    },
    {
      "author": "IT_guy_gaming",
      "role": "member",
      "date": "2026-09-12",
      "body": "Followed this thread before cranking every toggle — first growth session night actually went smooth."
    },
    {
      "author": "defender_hater",
      "role": "member",
      "date": "2026-09-13",
      "body": "Expected magic — still died to a sound flank. ESP does not replace headphones."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-14",
      "body": "@defender_hater — ESP does not replace audio. Keep radar range moderate and OOF arrows on so you still rotate when someone sprints your blind side.",
      "replyToAuthor": "defender_hater"
    },
    {
      "author": "ridge_runner",
      "role": "member",
      "date": "2026-09-14",
      "body": "Visible check + low FOV like you said. Nobody typed a word in post-match chat."
    },
    {
      "author": "Isle Guides Support",
      "role": "moderator",
      "date": "2026-09-16",
      "body": "@ridge_runner — visible check plus tighter FOV is the usual fix for quiet kill cams. Screenshot your menu once so you can restore the same numbers after patches. (Follow-up #2 — still locked; use Support for account-specific issues.)",
      "replyToAuthor": "ridge_runner"
    },
    {
      "author": "Kestrel_09",
      "role": "member",
      "date": "2026-09-15",
      "body": "Vehicle occupied flag saved us from a bait truck. Worth reading before enabling everything."
    },
    {
      "author": "m4rtin.l",
      "role": "member",
      "date": "2026-09-16",
      "body": "Skipped antivirus step, menu never opened. My fault but frustrating hour wasted."
    }
  ],
  "customizing-esp-colors": [
    {
      "author": "Isle Guides Editor",
      "role": "editor",
      "date": "2026-09-10",
      "body": "Pinned reference for customizing esp colors. Do not copy old FOV screenshots from Discord; use the checklist in the opening post."
    },
    {
      "author": "twitch_isle",
      "role": "member",
      "date": "2026-09-12",
      "body": "Vehicle occupied flag saved us from a bait truck. Worth reading before enabling everything."
    },
    {
      "author": "solo_q_isle",
      "role": "member",
      "date": "2026-09-13",
      "body": "Wide FOV got me roasted in squad Discord kill cam. Dialed back per guide."
    },
    {
      "author": "Forum Moderator",
      "role": "moderator",
      "date": "2026-09-14",
      "body": "@solo_q_isle — wide FOV plus low smooth reads obvious on kill cam. Cut FOV roughly in half, raise smooth, and keep visible check on — the aimbot section in this thread has sane starting numbers.",
      "replyToAuthor": "solo_q_isle"
    },
    {
      "author": "MoneyKing",
      "role": "member",
      "date": "2026-09-14",
      "body": "Saved config after first run — second login was two clicks. Wish I did that day one."
    },
    {
      "author": "Isle Guides Support",
      "role": "moderator",
      "date": "2026-09-16",
      "body": "@MoneyKing — good call saving a profile. Name configs by mode (ESP-only vs full assist) so you are not re-toggling mid-queue when your squad swaps roles. (Follow-up #2 — still locked; use Support for account-specific issues.)",
      "replyToAuthor": "MoneyKing"
    },
    {
      "author": "irritated_panda",
      "role": "member",
      "date": "2026-09-15",
      "body": "Status page said Active, loader matched, ESP came up first try on Win11."
    }
  ]
}

export function getForumReplies(slug: string): ForumReply[] {
  return FORUM_REPLIES[slug] ?? []
}
